const fs = require('fs');
const path = require('path');
const seed = require('./magazine-seed');

const TABLES_SQLITE = `
CREATE TABLE IF NOT EXISTS magazine_categories (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    parent_id INTEGER,
    description TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (parent_id) REFERENCES magazine_categories(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_magazine_categories_parent ON magazine_categories(parent_id);

CREATE TABLE IF NOT EXISTS magazine_tags (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS magazine_authors (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    photo_url TEXT,
    specialty TEXT,
    bio TEXT,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS magazine_posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    type TEXT NOT NULL DEFAULT 'article',
    title TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    summary TEXT,
    content TEXT,
    featured_image_url TEXT,
    category_id INTEGER,
    video_url TEXT,
    video_embed_url TEXT,
    video_file_url TEXT,
    captions_url TEXT,
    video_qualities TEXT,
    audio_url TEXT,
    audio_file_url TEXT,
    transcript TEXT,
    duration_seconds INTEGER NOT NULL DEFAULT 0,
    view_count INTEGER NOT NULL DEFAULT 0,
    published INTEGER NOT NULL DEFAULT 1,
    featured INTEGER NOT NULL DEFAULT 0,
    featured_order INTEGER NOT NULL DEFAULT 0,
    reading_time_minutes INTEGER NOT NULL DEFAULT 1,
    seo_title TEXT,
    seo_description TEXT,
    source_table TEXT,
    source_id INTEGER,
    created_at TEXT,
    updated_at TEXT,
    published_at TEXT,
    FOREIGN KEY (category_id) REFERENCES magazine_categories(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_magazine_posts_type ON magazine_posts(type, published, created_at);
CREATE INDEX IF NOT EXISTS idx_magazine_posts_category ON magazine_posts(category_id);
CREATE INDEX IF NOT EXISTS idx_magazine_posts_featured ON magazine_posts(featured, featured_order);

CREATE TABLE IF NOT EXISTS magazine_post_tags (
    post_id INTEGER NOT NULL,
    tag_id INTEGER NOT NULL,
    PRIMARY KEY (post_id, tag_id),
    FOREIGN KEY (post_id) REFERENCES magazine_posts(id) ON DELETE CASCADE,
    FOREIGN KEY (tag_id) REFERENCES magazine_tags(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS magazine_post_authors (
    post_id INTEGER NOT NULL,
    author_id INTEGER NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (post_id, author_id),
    FOREIGN KEY (post_id) REFERENCES magazine_posts(id) ON DELETE CASCADE,
    FOREIGN KEY (author_id) REFERENCES magazine_authors(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS magazine_related_posts (
    post_id INTEGER NOT NULL,
    related_post_id INTEGER NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (post_id, related_post_id),
    FOREIGN KEY (post_id) REFERENCES magazine_posts(id) ON DELETE CASCADE,
    FOREIGN KEY (related_post_id) REFERENCES magazine_posts(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS magazine_comments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    post_id INTEGER NOT NULL,
    parent_id INTEGER,
    user_id INTEGER,
    author_name TEXT,
    author_email TEXT,
    author_phone TEXT,
    body TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    is_staff INTEGER NOT NULL DEFAULT 0,
    created_at TEXT,
    FOREIGN KEY (post_id) REFERENCES magazine_posts(id) ON DELETE CASCADE,
    FOREIGN KEY (parent_id) REFERENCES magazine_comments(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_magazine_comments_post ON magazine_comments(post_id, status, created_at);

CREATE TABLE IF NOT EXISTS magazine_banners (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    placement TEXT NOT NULL,
    title TEXT,
    subtitle TEXT,
    category TEXT,
    image_url TEXT,
    link TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    expires_at TEXT,
    impressions INTEGER NOT NULL DEFAULT 0,
    clicks INTEGER NOT NULL DEFAULT 0,
    active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_magazine_banners_placement ON magazine_banners(placement, active, sort_order);
`;

const TABLES_PG = `
CREATE TABLE IF NOT EXISTS magazine_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    parent_id BIGINT,
    description TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (parent_id) REFERENCES magazine_categories(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_magazine_categories_parent ON magazine_categories(parent_id);

CREATE TABLE IF NOT EXISTS magazine_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS magazine_authors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    photo_url TEXT,
    specialty TEXT,
    bio TEXT,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS magazine_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL DEFAULT 'article',
    title TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    summary TEXT,
    content TEXT,
    featured_image_url TEXT,
    category_id BIGINT,
    video_url TEXT,
    video_embed_url TEXT,
    video_file_url TEXT,
    captions_url TEXT,
    video_qualities TEXT,
    audio_url TEXT,
    audio_file_url TEXT,
    transcript TEXT,
    duration_seconds INTEGER NOT NULL DEFAULT 0,
    view_count INTEGER NOT NULL DEFAULT 0,
    published INTEGER NOT NULL DEFAULT 1,
    featured INTEGER NOT NULL DEFAULT 0,
    featured_order INTEGER NOT NULL DEFAULT 0,
    reading_time_minutes INTEGER NOT NULL DEFAULT 1,
    seo_title TEXT,
    seo_description TEXT,
    source_table TEXT,
    source_id BIGINT,
    created_at TEXT,
    updated_at TEXT,
    published_at TEXT,
    FOREIGN KEY (category_id) REFERENCES magazine_categories(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_magazine_posts_type ON magazine_posts(type, published, created_at);
CREATE INDEX IF NOT EXISTS idx_magazine_posts_category ON magazine_posts(category_id);
CREATE INDEX IF NOT EXISTS idx_magazine_posts_featured ON magazine_posts(featured, featured_order);

CREATE TABLE IF NOT EXISTS magazine_post_tags (
    post_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    PRIMARY KEY (post_id, tag_id),
    FOREIGN KEY (post_id) REFERENCES magazine_posts(id) ON DELETE CASCADE,
    FOREIGN KEY (tag_id) REFERENCES magazine_tags(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS magazine_post_authors (
    post_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (post_id, author_id),
    FOREIGN KEY (post_id) REFERENCES magazine_posts(id) ON DELETE CASCADE,
    FOREIGN KEY (author_id) REFERENCES magazine_authors(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS magazine_related_posts (
    post_id BIGINT NOT NULL,
    related_post_id BIGINT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (post_id, related_post_id),
    FOREIGN KEY (post_id) REFERENCES magazine_posts(id) ON DELETE CASCADE,
    FOREIGN KEY (related_post_id) REFERENCES magazine_posts(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS magazine_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    parent_id BIGINT,
    user_id BIGINT,
    author_name TEXT,
    author_email TEXT,
    author_phone TEXT,
    body TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    is_staff INTEGER NOT NULL DEFAULT 0,
    created_at TEXT,
    FOREIGN KEY (post_id) REFERENCES magazine_posts(id) ON DELETE CASCADE,
    FOREIGN KEY (parent_id) REFERENCES magazine_comments(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_magazine_comments_post ON magazine_comments(post_id, status, created_at);

CREATE TABLE IF NOT EXISTS magazine_banners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placement TEXT NOT NULL,
    title TEXT,
    subtitle TEXT,
    category TEXT,
    image_url TEXT,
    link TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    expires_at TEXT,
    impressions INTEGER NOT NULL DEFAULT 0,
    clicks INTEGER NOT NULL DEFAULT 0,
    active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_magazine_banners_placement ON magazine_banners(placement, active, sort_order);
`;

function asBool(value) {
    return value === 1 || value === true || value === '1' || value === 't' || value === 'true';
}

function parseJson(value, fallback) {
    if (value == null || value === '') return fallback;
    if (typeof value === 'object') return value;
    try {
        return JSON.parse(value);
    } catch (_) {
        return fallback;
    }
}

function nowIso() {
    return new Date().toISOString();
}

function uploadsDir() {
    return path.join(__dirname, 'uploads');
}

function publicUpload(filename) {
    return `/uploads/${filename}`;
}

function mapCategory(row) {
    if (!row) return null;
    return {
        id: Number(row.id),
        name: row.name,
        slug: row.slug,
        parentId: row.parent_id == null ? null : Number(row.parent_id),
        description: row.description || '',
        sortOrder: Number(row.sort_order || 0)
    };
}

function mapTag(row) {
    if (!row) return null;
    return { id: Number(row.id), name: row.name, slug: row.slug };
}

function mapAuthor(row) {
    if (!row) return null;
    return {
        id: Number(row.id),
        userId: row.user_id == null ? null : Number(row.user_id),
        firstName: row.first_name,
        lastName: row.last_name,
        fullName: `${row.first_name || ''} ${row.last_name || ''}`.trim(),
        slug: row.slug,
        photoUrl: row.photo_url || '',
        specialty: row.specialty || '',
        bio: row.bio || ''
    };
}

function mapPost(row, extras = {}) {
    if (!row) return null;
    const durationSeconds = Number(row.duration_seconds || 0);
    const type = row.type || 'article';
    return {
        id: Number(row.id),
        type,
        title: row.title,
        slug: row.slug,
        summary: row.summary || '',
        content: row.content || '',
        featuredImageUrl: row.featured_image_url || row.image_url || '',
        imageUrl: row.featured_image_url || row.image_url || '',
        categoryId: row.category_id == null ? null : Number(row.category_id),
        category: extras.category || (row.category_name ? {
            id: Number(row.category_id),
            name: row.category_name,
            slug: row.category_slug
        } : null),
        categoryName: (extras.category && extras.category.name) || row.category_name || '',
        videoUrl: row.video_url || '',
        videoEmbedUrl: row.video_embed_url || '',
        videoFileUrl: row.video_file_url || '',
        captionsUrl: row.captions_url || '',
        videoQualities: parseJson(row.video_qualities, []),
        audioUrl: row.audio_url || '',
        audioFileUrl: row.audio_file_url || '',
        url: row.video_file_url || row.video_url || row.audio_file_url || row.audio_url || '',
        thumbnailUrl: row.featured_image_url || '',
        transcript: row.transcript || '',
        durationSeconds,
        duration: durationSeconds ? seed.formatDuration(durationSeconds) : '',
        viewCount: Number(row.view_count || 0),
        published: asBool(row.published),
        featured: asBool(row.featured),
        featuredOrder: Number(row.featured_order || 0),
        readingTimeMinutes: Number(row.reading_time_minutes || 1),
        listeningTimeMinutes: durationSeconds ? Math.max(1, Math.round(durationSeconds / 60)) : 0,
        seoTitle: row.seo_title || row.title,
        seoDescription: row.seo_description || row.summary || '',
        createdAt: row.created_at,
        updatedAt: row.updated_at,
        publishedAt: row.published_at || row.created_at,
        tags: extras.tags || [],
        authors: extras.authors || [],
        relatedIds: extras.relatedIds || [],
        related: extras.related || [],
        comments: extras.comments,
        breadcrumbs: extras.breadcrumbs || []
    };
}

function mapComment(row) {
    if (!row) return null;
    const staff = asBool(row.is_staff) || asBool(row.is_admin);
    return {
        id: Number(row.id),
        postId: Number(row.post_id),
        parentId: row.parent_id == null ? null : Number(row.parent_id),
        userId: row.user_id == null ? null : Number(row.user_id),
        authorName: row.author_name || [row.first_name, row.last_name].filter(Boolean).join(' ') || 'کاربر تات کیدز',
        body: row.body,
        status: row.status,
        isStaff: staff,
        badge: staff ? (asBool(row.is_admin) ? 'ادمین' : 'نویسنده') : null,
        createdAt: row.created_at,
        replies: []
    };
}

function mapBanner(row) {
    if (!row) return null;
    return {
        id: Number(row.id),
        placement: row.placement,
        title: row.title || '',
        subtitle: row.subtitle || '',
        category: row.category || '',
        imageUrl: row.image_url || '',
        link: row.link || '',
        sortOrder: Number(row.sort_order || 0),
        expiresAt: row.expires_at || null,
        impressions: Number(row.impressions || 0),
        clicks: Number(row.clicks || 0),
        active: asBool(row.active),
        createdAt: row.created_at
    };
}

function nestComments(flat) {
    const byId = new Map();
    flat.forEach((item) => byId.set(item.id, { ...item, replies: [] }));
    const roots = [];
    byId.forEach((item) => {
        if (item.parentId && byId.has(item.parentId)) byId.get(item.parentId).replies.push(item);
        else roots.push(item);
    });
    return roots;
}

function buildCategoryTree(rows) {
    const items = rows.map(mapCategory);
    const byId = new Map(items.map((item) => [item.id, { ...item, children: [] }]));
    const roots = [];
    byId.forEach((item) => {
        if (item.parentId && byId.has(item.parentId)) byId.get(item.parentId).children.push(item);
        else roots.push(item);
    });
    const sortFn = (a, b) => a.sortOrder - b.sortOrder || a.id - b.id;
    const sortTree = (nodes) => {
        nodes.sort(sortFn);
        nodes.forEach((node) => sortTree(node.children));
    };
    sortTree(roots);
    return roots;
}

function uniqueSlugSqlite(db, table, slug, exceptId) {
    let candidate = slug;
    let n = 2;
    while (true) {
        const row = exceptId
            ? db.prepare(`SELECT id FROM ${table} WHERE slug = ? AND id != ?`).get(candidate, exceptId)
            : db.prepare(`SELECT id FROM ${table} WHERE slug = ?`).get(candidate);
        if (!row) return candidate;
        candidate = `${slug}-${n}`;
        n += 1;
    }
}

async function uniqueSlugPg(one, table, slug, exceptId) {
    let candidate = slug;
    let n = 2;
    while (true) {
        const row = exceptId
            ? await one(`SELECT id FROM ${table} WHERE slug = $1 AND id != $2`, [candidate, exceptId])
            : await one(`SELECT id FROM ${table} WHERE slug = $1`, [candidate]);
        if (!row) return candidate;
        candidate = `${slug}-${n}`;
        n += 1;
    }
}

function ensureMediaFiles() {
    const dir = uploadsDir();
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    const wav = path.join(dir, 'magazine-sample.wav');
    if (!fs.existsSync(wav)) seed.writeSilentWav(wav, 12);
    const vtt = path.join(dir, 'magazine-sample.vtt');
    if (!fs.existsSync(vtt)) seed.writeVttCaptions(vtt, 'آموزش سلامت کودک');
    return {
        audio: publicUpload('magazine-sample.wav'),
        captions: publicUpload('magazine-sample.vtt')
    };
}

function placeholderImage(filename, title, color) {
    const filePath = path.join(uploadsDir(), filename);
    if (!fs.existsSync(filePath)) seed.writeSvgPlaceholder(filePath, title, color);
    return publicUpload(filename);
}

function seedTaxonomySqlite(db) {
    const insertCat = db.prepare(`
        INSERT INTO magazine_categories (name, slug, parent_id, sort_order)
        VALUES (?, ?, ?, ?)
        ON CONFLICT(slug) DO UPDATE SET name = excluded.name
    `);
    const getCat = db.prepare('SELECT id FROM magazine_categories WHERE slug = ?');
    CATEGORY_TREE_WALK(seed.CATEGORY_TREE, null, (node, parentId, order) => {
        insertCat.run(node.name, node.slug, parentId, order);
        const row = getCat.get(node.slug);
        return row ? Number(row.id) : null;
    });
    const insertTag = db.prepare(`
        INSERT INTO magazine_tags (name, slug) VALUES (?, ?)
        ON CONFLICT(slug) DO UPDATE SET name = excluded.name
    `);
    seed.TAGS.forEach((tag) => insertTag.run(tag.name, tag.slug));
    const insertAuthor = db.prepare(`
        INSERT INTO magazine_authors (first_name, last_name, slug, specialty, bio, photo_url)
        VALUES (?, ?, ?, ?, ?, ?)
        ON CONFLICT(slug) DO UPDATE SET
            first_name = excluded.first_name,
            last_name = excluded.last_name,
            specialty = excluded.specialty,
            bio = excluded.bio
    `);
    const colors = ['#0f766e', '#0d9488', '#115e59'];
    seed.AUTHORS.forEach((author, index) => {
        const photo = placeholderImage(`magazine-author-${author.slug}.svg`, author.firstName, colors[index % colors.length]);
        insertAuthor.run(author.firstName, author.lastName, author.slug, author.specialty, author.bio, photo);
    });
    const editorial = db.prepare('SELECT id FROM magazine_authors WHERE slug = ?').get('tatkids-editorial');
    const admin = db.prepare('SELECT id FROM users WHERE is_admin = 1 ORDER BY id LIMIT 1').get();
    if (editorial && admin) {
        db.prepare('UPDATE magazine_authors SET user_id = ? WHERE id = ?').run(admin.id, editorial.id);
    }
}

async function seedTaxonomyPg(q, one) {
    const walk = async (nodes, parentId) => {
        for (let i = 0; i < nodes.length; i += 1) {
            const node = nodes[i];
            await q(
                `INSERT INTO magazine_categories (name, slug, parent_id, sort_order)
                 VALUES ($1,$2,$3,$4)
                 ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name`,
                [node.name, node.slug, parentId, i]
            );
            const row = await one('SELECT id FROM magazine_categories WHERE slug = $1', [node.slug]);
            if (node.children && node.children.length) await walk(node.children, Number(row.id));
        }
    };
    await walk(seed.CATEGORY_TREE, null);
    for (const tag of seed.TAGS) {
        await q(
            `INSERT INTO magazine_tags (name, slug) VALUES ($1,$2)
             ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name`,
            [tag.name, tag.slug]
        );
    }
    const colors = ['#0f766e', '#0d9488', '#115e59'];
    for (let i = 0; i < seed.AUTHORS.length; i += 1) {
        const author = seed.AUTHORS[i];
        const photo = placeholderImage(`magazine-author-${author.slug}.svg`, author.firstName, colors[i % colors.length]);
        await q(
            `INSERT INTO magazine_authors (first_name, last_name, slug, specialty, bio, photo_url)
             VALUES ($1,$2,$3,$4,$5,$6)
             ON CONFLICT (slug) DO UPDATE SET
                first_name = EXCLUDED.first_name,
                last_name = EXCLUDED.last_name,
                specialty = EXCLUDED.specialty,
                bio = EXCLUDED.bio`,
            [author.firstName, author.lastName, author.slug, author.specialty, author.bio, photo]
        );
    }
    const editorial = await one('SELECT id FROM magazine_authors WHERE slug = $1', ['tatkids-editorial']);
    const admin = await one('SELECT id FROM users WHERE is_admin = 1 ORDER BY id LIMIT 1');
    if (editorial && admin) {
        await q('UPDATE magazine_authors SET user_id = $1 WHERE id = $2', [admin.id, editorial.id]);
    }
}

function CATEGORY_TREE_WALK(nodes, parentId, visit) {
    nodes.forEach((node, index) => {
        const id = visit(node, parentId, index);
        if (node.children && node.children.length) CATEGORY_TREE_WALK(node.children, id, visit);
    });
}

function tagIdsForPostSqlite(db, type, title, categorySlug) {
    const wanted = [];
    if (/خواب|نوزاد/.test(title)) wanted.push('sleep', 'newborn');
    if (/تغذیه|آهن|میان‌وعده|غذا/.test(title)) wanted.push('child-nutrition', 'brain-development');
    if (/اضطراب|تربیت|اجتماعی|قشقرق/.test(title)) wanted.push('anxiety');
    if (/بازی|مهارت/.test(title)) wanted.push('play');
    if (/سرماخوردگی|تب|بیماری/.test(title)) wanted.push('safety');
    if (type === 'video') wanted.push('play');
    if (categorySlug === 'nutrition') wanted.push('child-nutrition');
    const slugs = [...new Set(wanted.length ? wanted : ['play'])];
    return slugs.map((slug) => {
        const row = db.prepare('SELECT id FROM magazine_tags WHERE slug = ?').get(slug);
        return row ? Number(row.id) : null;
    }).filter(Boolean);
}

function pickAuthorIdsSqlite(db, type, title) {
    const ahmadi = db.prepare('SELECT id FROM magazine_authors WHERE slug = ?').get('dr-sara-ahmadi');
    const karimi = db.prepare('SELECT id FROM magazine_authors WHERE slug = ?').get('dr-reza-karimi');
    const editorial = db.prepare('SELECT id FROM magazine_authors WHERE slug = ?').get('tatkids-editorial');
    if (/اضطراب|روان|تربیت|اجتماعی|قشقرق/.test(title) && ahmadi) return [Number(ahmadi.id)];
    if (/تغذیه|آهن|غذا|میان‌وعده/.test(title) && karimi) return [Number(karimi.id)];
    if (type === 'podcast' && ahmadi && editorial) return [Number(ahmadi.id), Number(editorial.id)];
    return [Number((editorial || ahmadi || karimi).id)];
}

function migrateLegacySqlite(db) {
    const count = db.prepare('SELECT COUNT(*) AS n FROM magazine_posts').get().n;
    if (count > 0) {
        seedRelatedAndCommentsSqlite(db);
        seedBannersSqlite(db);
        return;
    }
    const news = db.prepare('SELECT * FROM news ORDER BY id').all();
    const videos = db.prepare('SELECT * FROM videos ORDER BY id').all();
    const podcasts = db.prepare('SELECT * FROM podcasts ORDER BY id').all();
    if (!news.length && !videos.length && !podcasts.length) return;
    const media = ensureMediaFiles();
    const insertPost = db.prepare(`
        INSERT INTO magazine_posts (
            id, type, title, slug, summary, content, featured_image_url, category_id,
            video_url, video_embed_url, video_file_url, captions_url, video_qualities,
            audio_url, audio_file_url, transcript, duration_seconds, view_count,
            published, featured, featured_order, reading_time_minutes, seo_title, seo_description,
            source_table, source_id, created_at, updated_at, published_at
        ) VALUES (
            @id, @type, @title, @slug, @summary, @content, @featured_image_url, @category_id,
            @video_url, @video_embed_url, @video_file_url, @captions_url, @video_qualities,
            @audio_url, @audio_file_url, @transcript, @duration_seconds, @view_count,
            @published, @featured, @featured_order, @reading_time_minutes, @seo_title, @seo_description,
            @source_table, @source_id, @created_at, @updated_at, @published_at
        )
    `);
    const attachTag = db.prepare('INSERT OR IGNORE INTO magazine_post_tags (post_id, tag_id) VALUES (?, ?)');
    const attachAuthor = db.prepare('INSERT OR IGNORE INTO magazine_post_authors (post_id, author_id, sort_order) VALUES (?, ?, ?)');

    news.forEach((item, index) => {
        const mappedSlug = seed.LEGACY_CATEGORY_MAP[item.category] || 'mother-child';
        const category = db.prepare('SELECT id FROM magazine_categories WHERE slug = ?').get(mappedSlug);
        const slug = uniqueSlugSqlite(db, 'magazine_posts', seed.slugify(item.title, `article-${item.id}`));
        const content = seed.articleHtml(item.title, item.summary);
        const image = item.image_url || placeholderImage(`magazine-article-${item.id}.svg`, item.title, '#0f766e');
        insertPost.run({
            id: item.id,
            type: 'article',
            title: item.title,
            slug,
            summary: item.summary,
            content,
            featured_image_url: image,
            category_id: category ? category.id : null,
            video_url: null,
            video_embed_url: null,
            video_file_url: null,
            captions_url: null,
            video_qualities: null,
            audio_url: null,
            audio_file_url: null,
            transcript: null,
            duration_seconds: 0,
            view_count: Math.max(12, 80 - (index * 7)),
            published: 1,
            featured: index < 4 ? 1 : 0,
            featured_order: index < 4 ? index + 1 : 0,
            reading_time_minutes: seed.readingTimeMinutes(content, item.summary),
            seo_title: `${item.title} | مجله سلامت تات کیدز`,
            seo_description: item.summary,
            source_table: 'news',
            source_id: item.id,
            created_at: item.created_at,
            updated_at: item.updated_at || item.created_at,
            published_at: item.created_at
        });
        tagIdsForPostSqlite(db, 'article', item.title, mappedSlug).forEach((tagId) => attachTag.run(item.id, tagId));
        pickAuthorIdsSqlite(db, 'article', item.title).forEach((authorId, order) => attachAuthor.run(item.id, authorId, order));
    });

    const maxNewsId = news.reduce((max, item) => Math.max(max, Number(item.id) || 0), 0);
    videos.forEach((item, index) => {
        const id = maxNewsId + index + 1;
        const category = db.prepare('SELECT id FROM magazine_categories WHERE slug = ?').get('education');
        const slug = uniqueSlugSqlite(db, 'magazine_posts', seed.slugify(item.title, `video-${item.id}`));
        const content = seed.videoHtml(item.title);
        const image = item.thumbnail_url || placeholderImage(`magazine-video-${item.id}.svg`, item.title, '#0d9488');
        const embed = seed.toEmbedUrl(item.url);
        insertPost.run({
            id,
            type: 'video',
            title: item.title,
            slug,
            summary: item.summary,
            content,
            featured_image_url: image,
            category_id: category ? category.id : null,
            video_url: item.url,
            video_embed_url: embed,
            video_file_url: null,
            captions_url: media.captions,
            video_qualities: JSON.stringify([
                { label: 'خودکار', url: embed || item.url },
                { label: '۷۲۰p', url: embed || item.url },
                { label: '۴۸۰p', url: embed || item.url }
            ]),
            audio_url: null,
            audio_file_url: null,
            transcript: null,
            duration_seconds: 180 + (index * 25),
            view_count: 40 + (index * 5),
            published: 1,
            featured: 0,
            featured_order: 0,
            reading_time_minutes: seed.readingTimeMinutes(content, item.summary),
            seo_title: `${item.title} | ویدیو مجله سلامت`,
            seo_description: item.summary,
            source_table: 'videos',
            source_id: item.id,
            created_at: item.created_at,
            updated_at: item.created_at,
            published_at: item.created_at
        });
        tagIdsForPostSqlite(db, 'video', item.title, 'education').forEach((tagId) => attachTag.run(id, tagId));
        pickAuthorIdsSqlite(db, 'video', item.title).forEach((authorId, order) => attachAuthor.run(id, authorId, order));
    });

    const afterVideos = maxNewsId + videos.length;
    podcasts.forEach((item, index) => {
        const id = afterVideos + index + 1;
        const category = db.prepare('SELECT id FROM magazine_categories WHERE slug = ?').get('mental-health');
        const slug = uniqueSlugSqlite(db, 'magazine_posts', seed.slugify(item.title, `podcast-${item.id}`));
        const content = seed.podcastHtml(item.title);
        const image = item.thumbnail_url || placeholderImage(`magazine-podcast-${item.id}.svg`, item.title, '#115e59');
        const durationSeconds = seed.parseDurationSeconds(item.duration) || 12;
        insertPost.run({
            id,
            type: 'podcast',
            title: item.title,
            slug,
            summary: item.summary,
            content,
            featured_image_url: image,
            category_id: category ? category.id : null,
            video_url: null,
            video_embed_url: null,
            video_file_url: null,
            captions_url: null,
            video_qualities: null,
            audio_url: item.url,
            audio_file_url: media.audio,
            transcript: seed.defaultTranscript(item.title),
            duration_seconds: durationSeconds,
            view_count: 30 + (index * 8),
            published: 1,
            featured: 0,
            featured_order: 0,
            reading_time_minutes: seed.readingTimeMinutes(content, item.summary),
            seo_title: `${item.title} | پادکست مجله سلامت`,
            seo_description: item.summary,
            source_table: 'podcasts',
            source_id: item.id,
            created_at: item.created_at,
            updated_at: item.created_at,
            published_at: item.created_at
        });
        tagIdsForPostSqlite(db, 'podcast', item.title, 'mental-health').forEach((tagId) => attachTag.run(id, tagId));
        pickAuthorIdsSqlite(db, 'podcast', item.title).forEach((authorId, order) => attachAuthor.run(id, authorId, order));
    });

    const maxId = db.prepare('SELECT MAX(id) AS n FROM magazine_posts').get().n || 0;
    try {
        const seq = db.prepare("SELECT seq FROM sqlite_sequence WHERE name = 'magazine_posts'").get();
        if (!seq) {
            db.prepare("INSERT INTO sqlite_sequence (name, seq) VALUES ('magazine_posts', ?)").run(maxId);
        } else {
            db.prepare("UPDATE sqlite_sequence SET seq = ? WHERE name = 'magazine_posts'").run(maxId);
        }
    } catch (_) { /* ignore */ }

    seedRelatedAndCommentsSqlite(db);
    seedBannersSqlite(db);
}

function seedRelatedAndCommentsSqlite(db) {
    const posts = db.prepare('SELECT id, category_id FROM magazine_posts WHERE type = ? ORDER BY id').all('article');
    const insertRelated = db.prepare('INSERT OR IGNORE INTO magazine_related_posts (post_id, related_post_id, sort_order) VALUES (?, ?, ?)');
    posts.forEach((post) => {
        const related = db.prepare(`
            SELECT id FROM magazine_posts
            WHERE id != ? AND published = 1 AND (category_id = ? OR type = 'article')
            ORDER BY view_count DESC, created_at DESC LIMIT 3
        `).all(post.id, post.category_id);
        related.forEach((item, index) => insertRelated.run(post.id, item.id, index));
    });

    const commentCount = db.prepare('SELECT COUNT(*) AS n FROM magazine_comments').get().n;
    if (commentCount > 0 || !posts.length) return;
    const first = posts[0];
    const editorial = db.prepare('SELECT id, user_id FROM magazine_authors WHERE slug = ?').get('tatkids-editorial');
    const now = nowIso();
    const insertComment = db.prepare(`
        INSERT INTO magazine_comments (post_id, parent_id, user_id, author_name, author_email, body, status, is_staff, created_at)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
    `);
    const parent = insertComment.run(
        first.id, null, null, 'مریم رضایی', 'maryam@example.com',
        'خیلی مفید بود؛ روتین خواب فرزندم بعد از این نکات بهتر شده.',
        'approved', 0, now
    );
    insertComment.run(
        first.id, parent.lastInsertRowid, editorial ? editorial.user_id : null, 'تیم تحریریه تات کیدز', '',
        'خوشحالیم که کمک کرده. اگر الگوی خواب دوباره به هم ریخت، با پزشک کودک هم هماهنگ کنید.',
        'approved', 1, now
    );
    insertComment.run(
        first.id, null, null, 'علی محمدی', 'ali@example.com',
        'لطفاً درباره خواب در مسافرت هم بنویسید.',
        'pending', 0, now
    );
}

function seedBannersSqlite(db) {
    const insert = db.prepare(`
        INSERT INTO magazine_banners (placement, title, subtitle, category, image_url, link, sort_order, expires_at, active, created_at)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, 1, ?)
    `);
    const heroCount = db.prepare("SELECT COUNT(*) AS n FROM magazine_banners WHERE placement = 'hero'").get().n;
    if (heroCount === 0) {
        const featured = db.prepare(`
            SELECT id, title, slug, category_id FROM magazine_posts WHERE featured = 1 ORDER BY featured_order, id LIMIT 4
        `).all();
        featured.forEach((post, index) => {
            const cat = post.category_id
                ? db.prepare('SELECT name FROM magazine_categories WHERE id = ?').get(post.category_id)
                : null;
            insert.run(
                'hero',
                post.title,
                'مقاله منتخب مجله سلامت',
                cat ? cat.name : '',
                placeholderImage(`magazine-hero-${post.id}.svg`, post.title, '#0f766e'),
                `/news/${post.id}`,
                index + 1,
                null,
                nowIso()
            );
        });
    }
    const adCount = db.prepare("SELECT COUNT(*) AS n FROM magazine_banners WHERE placement LIKE 'sidebar%'").get().n;
    if (adCount > 0) return;
    const future = new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString();
    insert.run(
        'sidebar-300x250',
        'فروشگاه تات کیدز',
        'انتخاب محصول بر اساس سن و مهارت رشدی',
        'فروشگاه',
        placeholderImage('magazine-ad-250.svg', 'فروشگاه تات کیدز', '#d97706'),
        '/shop',
        1,
        future,
        nowIso()
    );
    insert.run(
        'sidebar-300x600',
        'پایش رشد کودک',
        'قد، وزن و دور سر را با نمودار استاندارد دنبال کنید',
        'رشد',
        placeholderImage('magazine-ad-600.svg', 'نمودار رشد', '#0f766e'),
        '/dashboard',
        2,
        future,
        nowIso()
    );
}

function sqliteApi(db) {
    const listCategoryRows = () => db.prepare('SELECT * FROM magazine_categories ORDER BY sort_order, id').all();

    function postTags(postId) {
        return db.prepare(`
            SELECT t.* FROM magazine_tags t
            JOIN magazine_post_tags pt ON pt.tag_id = t.id
            WHERE pt.post_id = ?
            ORDER BY t.name
        `).all(postId).map(mapTag);
    }

    function postAuthors(postId) {
        return db.prepare(`
            SELECT a.* FROM magazine_authors a
            JOIN magazine_post_authors pa ON pa.author_id = a.id
            WHERE pa.post_id = ?
            ORDER BY pa.sort_order, a.id
        `).all(postId).map(mapAuthor);
    }

    function postRelatedIds(postId) {
        return db.prepare(`
            SELECT related_post_id AS id FROM magazine_related_posts
            WHERE post_id = ? ORDER BY sort_order, related_post_id
        `).all(postId).map((row) => Number(row.id));
    }

    function categoryById(id) {
        if (!id) return null;
        return mapCategory(db.prepare('SELECT * FROM magazine_categories WHERE id = ?').get(id));
    }

    function breadcrumbsFor(category) {
        const crumbs = [{ name: 'مجله سلامت', slug: '', href: '/news' }];
        if (!category) return crumbs;
        const chain = [];
        let current = category;
        const guard = new Set();
        while (current && !guard.has(current.id)) {
            guard.add(current.id);
            chain.unshift(current);
            current = current.parentId ? categoryById(current.parentId) : null;
        }
        chain.forEach((item) => crumbs.push({
            name: item.name,
            slug: item.slug,
            href: `/news/category/${item.slug}`
        }));
        return crumbs;
    }

    function hydrate(row, options = {}) {
        if (!row) return null;
        const category = categoryById(row.category_id);
        const extras = {
            category,
            tags: postTags(row.id),
            authors: postAuthors(row.id),
            relatedIds: postRelatedIds(row.id),
            breadcrumbs: breadcrumbsFor(category)
        };
        if (options.withRelated) extras.related = relatedPosts(row.id, extras.tags, row.category_id);
        if (options.withComments) extras.comments = listComments(row.id, { status: 'approved' });
        return mapPost(row, extras);
    }

    function listPosts(filters = {}) {
        const where = [];
        const params = [];
        if (filters.published !== false && !filters.includeUnpublished) {
            where.push('p.published = 1');
        }
        if (filters.type) {
            where.push('p.type = ?');
            params.push(filters.type);
        }
        if (filters.featured) where.push('p.featured = 1');
        if (filters.categorySlug) {
            const cat = db.prepare('SELECT id FROM magazine_categories WHERE slug = ?').get(filters.categorySlug);
            if (!cat) return [];
            const ids = [Number(cat.id)];
            listCategoryRows().forEach((row) => {
                if (Number(row.parent_id) === Number(cat.id)) ids.push(Number(row.id));
            });
            where.push(`p.category_id IN (${ids.map(() => '?').join(',')})`);
            params.push(...ids);
        }
        if (filters.tagSlug) {
            where.push(`EXISTS (
                SELECT 1 FROM magazine_post_tags pt
                JOIN magazine_tags t ON t.id = pt.tag_id
                WHERE pt.post_id = p.id AND t.slug = ?
            )`);
            params.push(filters.tagSlug);
        }
        if (filters.authorSlug) {
            where.push(`EXISTS (
                SELECT 1 FROM magazine_post_authors pa
                JOIN magazine_authors a ON a.id = pa.author_id
                WHERE pa.post_id = p.id AND a.slug = ?
            )`);
            params.push(filters.authorSlug);
        }
        if (filters.q) {
            where.push('(p.title LIKE ? OR p.summary LIKE ? OR p.content LIKE ?)');
            const like = `%${filters.q}%`;
            params.push(like, like, like);
        }
        const order = filters.sort === 'popular'
            ? 'p.view_count DESC, p.created_at DESC'
            : (filters.featured ? 'p.featured_order ASC, p.created_at DESC' : 'p.created_at DESC, p.id DESC');
        const sql = `
            SELECT p.*, c.name AS category_name, c.slug AS category_slug
            FROM magazine_posts p
            LEFT JOIN magazine_categories c ON c.id = p.category_id
            ${where.length ? `WHERE ${where.join(' AND ')}` : ''}
            ORDER BY ${order}
        `;
        return db.prepare(sql).all(...params).map((row) => hydrate(row));
    }

    function getPost(idOrSlug, options = {}) {
        const asId = Number(idOrSlug);
        const row = Number.isFinite(asId) && String(asId) === String(idOrSlug)
            ? db.prepare('SELECT * FROM magazine_posts WHERE id = ?').get(asId)
            : db.prepare('SELECT * FROM magazine_posts WHERE slug = ?').get(String(idOrSlug));
        if (!row && Number.isFinite(asId)) {
            const bySource = db.prepare(
                "SELECT * FROM magazine_posts WHERE source_table = 'news' AND source_id = ?"
            ).get(asId);
            if (bySource) return hydrate(bySource, { withRelated: true, withComments: true, ...options });
        }
        return hydrate(row, { withRelated: true, withComments: true, ...options });
    }

    function relatedPosts(postId, tags, categoryId) {
        const manual = db.prepare(`
            SELECT p.*, c.name AS category_name, c.slug AS category_slug
            FROM magazine_related_posts r
            JOIN magazine_posts p ON p.id = r.related_post_id
            LEFT JOIN magazine_categories c ON c.id = p.category_id
            WHERE r.post_id = ? AND p.published = 1
            ORDER BY r.sort_order
        `).all(postId).map((row) => mapPost(row, { tags: postTags(row.id), authors: postAuthors(row.id) }));
        if (manual.length >= 4) return manual.slice(0, 4);
        const tagIds = (tags || []).map((tag) => tag.id);
        const exclude = new Set([Number(postId), ...manual.map((item) => item.id)]);
        let extra = [];
        if (tagIds.length || categoryId) {
            extra = db.prepare(`
                SELECT p.*, c.name AS category_name, c.slug AS category_slug,
                    (
                        CASE WHEN p.category_id = ? THEN 3 ELSE 0 END +
                        (SELECT COUNT(*) FROM magazine_post_tags pt
                         WHERE pt.post_id = p.id AND pt.tag_id IN (${tagIds.length ? tagIds.map(() => '?').join(',') : 'NULL'}) )
                    ) AS score
                FROM magazine_posts p
                LEFT JOIN magazine_categories c ON c.id = p.category_id
                WHERE p.published = 1 AND p.id != ?
                ORDER BY score DESC, p.view_count DESC, p.created_at DESC
                LIMIT 8
            `).all(categoryId || 0, ...tagIds, postId);
        }
        extra.forEach((row) => {
            if (exclude.has(Number(row.id)) || manual.length + extra.length > 20) return;
            if (manual.length >= 4) return;
            exclude.add(Number(row.id));
            manual.push(mapPost(row, { tags: postTags(row.id), authors: postAuthors(row.id) }));
        });
        return manual.slice(0, 4);
    }

    function setPostRelations(postId, { tagIds, authorIds, relatedIds }) {
        if (Array.isArray(tagIds)) {
            db.prepare('DELETE FROM magazine_post_tags WHERE post_id = ?').run(postId);
            const ins = db.prepare('INSERT OR IGNORE INTO magazine_post_tags (post_id, tag_id) VALUES (?, ?)');
            tagIds.map(Number).filter(Boolean).forEach((tagId) => ins.run(postId, tagId));
        }
        if (Array.isArray(authorIds)) {
            db.prepare('DELETE FROM magazine_post_authors WHERE post_id = ?').run(postId);
            const ins = db.prepare('INSERT OR IGNORE INTO magazine_post_authors (post_id, author_id, sort_order) VALUES (?, ?, ?)');
            authorIds.map(Number).filter(Boolean).forEach((authorId, index) => ins.run(postId, authorId, index));
        }
        if (Array.isArray(relatedIds)) {
            db.prepare('DELETE FROM magazine_related_posts WHERE post_id = ?').run(postId);
            const ins = db.prepare('INSERT OR IGNORE INTO magazine_related_posts (post_id, related_post_id, sort_order) VALUES (?, ?, ?)');
            relatedIds.map(Number).filter((id) => id && id !== Number(postId)).forEach((id, index) => ins.run(postId, id, index));
        }
    }

    function savePost(payload, existing) {
        const type = payload.type || (existing && existing.type) || 'article';
        const title = payload.title || (existing && existing.title);
        const slug = uniqueSlugSqlite(
            db,
            'magazine_posts',
            seed.slugify(payload.slug || payload.title || (existing && existing.slug), 'post'),
            existing && existing.id
        );
        const content = payload.content != null ? payload.content : (existing && existing.content) || '';
        const summary = payload.summary != null ? payload.summary : (existing && existing.summary) || '';
        const durationSeconds = payload.durationSeconds != null
            ? Number(payload.durationSeconds)
            : seed.parseDurationSeconds(payload.duration) || (existing && existing.durationSeconds) || 0;
        const fields = {
            type,
            title,
            slug,
            summary,
            content,
            featured_image_url: payload.featuredImageUrl != null ? payload.featuredImageUrl : (existing && existing.featuredImageUrl) || null,
            category_id: payload.categoryId != null && payload.categoryId !== '' ? Number(payload.categoryId) : (existing ? existing.categoryId : null),
            video_url: payload.videoUrl != null ? payload.videoUrl : (existing && existing.videoUrl) || null,
            video_embed_url: payload.videoEmbedUrl != null ? payload.videoEmbedUrl : seed.toEmbedUrl(payload.videoUrl || (existing && existing.videoUrl)),
            video_file_url: payload.videoFileUrl != null ? payload.videoFileUrl : (existing && existing.videoFileUrl) || null,
            captions_url: payload.captionsUrl != null ? payload.captionsUrl : (existing && existing.captionsUrl) || null,
            video_qualities: payload.videoQualities
                ? JSON.stringify(payload.videoQualities)
                : (existing && existing.videoQualities && existing.videoQualities.length
                    ? JSON.stringify(existing.videoQualities)
                    : null),
            audio_url: payload.audioUrl != null ? payload.audioUrl : (existing && existing.audioUrl) || null,
            audio_file_url: payload.audioFileUrl != null ? payload.audioFileUrl : (existing && existing.audioFileUrl) || null,
            transcript: payload.transcript != null ? payload.transcript : (existing && existing.transcript) || null,
            duration_seconds: durationSeconds,
            published: payload.published == null ? (existing ? (existing.published ? 1 : 0) : 1) : (asBool(payload.published) ? 1 : 0),
            featured: payload.featured == null ? (existing ? (existing.featured ? 1 : 0) : 0) : (asBool(payload.featured) ? 1 : 0),
            featured_order: payload.featuredOrder != null ? Number(payload.featuredOrder) : (existing && existing.featuredOrder) || 0,
            reading_time_minutes: seed.readingTimeMinutes(content, summary),
            seo_title: payload.seoTitle != null ? payload.seoTitle : (existing && existing.seoTitle) || title,
            seo_description: payload.seoDescription != null ? payload.seoDescription : (existing && existing.seoDescription) || summary,
            updated_at: nowIso()
        };
        let id;
        if (existing) {
            id = Number(existing.id);
            db.prepare(`
                UPDATE magazine_posts SET
                    type=@type, title=@title, slug=@slug, summary=@summary, content=@content,
                    featured_image_url=@featured_image_url, category_id=@category_id,
                    video_url=@video_url, video_embed_url=@video_embed_url, video_file_url=@video_file_url,
                    captions_url=@captions_url, video_qualities=@video_qualities,
                    audio_url=@audio_url, audio_file_url=@audio_file_url, transcript=@transcript,
                    duration_seconds=@duration_seconds, published=@published, featured=@featured,
                    featured_order=@featured_order, reading_time_minutes=@reading_time_minutes,
                    seo_title=@seo_title, seo_description=@seo_description, updated_at=@updated_at
                WHERE id=@id
            `).run({ ...fields, id });
        } else {
            const created = nowIso();
            const info = db.prepare(`
                INSERT INTO magazine_posts (
                    type, title, slug, summary, content, featured_image_url, category_id,
                    video_url, video_embed_url, video_file_url, captions_url, video_qualities,
                    audio_url, audio_file_url, transcript, duration_seconds, view_count,
                    published, featured, featured_order, reading_time_minutes, seo_title, seo_description,
                    created_at, updated_at, published_at
                ) VALUES (
                    @type, @title, @slug, @summary, @content, @featured_image_url, @category_id,
                    @video_url, @video_embed_url, @video_file_url, @captions_url, @video_qualities,
                    @audio_url, @audio_file_url, @transcript, @duration_seconds, 0,
                    @published, @featured, @featured_order, @reading_time_minutes, @seo_title, @seo_description,
                    @created_at, @updated_at, @published_at
                )
            `).run({ ...fields, created_at: created, published_at: created });
            id = Number(info.lastInsertRowid);
        }
        setPostRelations(id, {
            tagIds: payload.tagIds,
            authorIds: payload.authorIds,
            relatedIds: payload.relatedIds
        });
        return getPost(id);
    }

    function listComments(postId, { status } = {}) {
        const rows = status && status !== 'all'
            ? db.prepare(`
                SELECT c.*, u.first_name, u.last_name, u.is_admin
                FROM magazine_comments c
                LEFT JOIN users u ON u.id = c.user_id
                WHERE c.post_id = ? AND c.status = ?
                ORDER BY c.created_at ASC, c.id ASC
            `).all(postId, status)
            : db.prepare(`
                SELECT c.*, u.first_name, u.last_name, u.is_admin
                FROM magazine_comments c
                LEFT JOIN users u ON u.id = c.user_id
                WHERE c.post_id = ?
                ORDER BY c.created_at ASC, c.id ASC
            `).all(postId);
        return nestComments(rows.map(mapComment));
    }

    function listBanners(placement) {
        const now = nowIso();
        const rows = placement && placement !== 'all'
            ? db.prepare(`
                SELECT * FROM magazine_banners
                WHERE active = 1 AND placement = ?
                  AND (expires_at IS NULL OR expires_at = '' OR expires_at > ?)
                ORDER BY sort_order, id
            `).all(placement, now)
            : db.prepare('SELECT * FROM magazine_banners ORDER BY placement, sort_order, id').all();
        return rows.map(mapBanner);
    }

    return {
        listCategories() {
            return buildCategoryTree(listCategoryRows());
        },
        flattenCategories() {
            return listCategoryRows().map(mapCategory);
        },
        createCategory(payload) {
            const slug = uniqueSlugSqlite(db, 'magazine_categories', seed.slugify(payload.slug || payload.name, 'category'));
            const info = db.prepare(`
                INSERT INTO magazine_categories (name, slug, parent_id, description, sort_order)
                VALUES (?, ?, ?, ?, ?)
            `).run(payload.name, slug, payload.parentId || null, payload.description || '', Number(payload.sortOrder || 0));
            return mapCategory(db.prepare('SELECT * FROM magazine_categories WHERE id = ?').get(info.lastInsertRowid));
        },
        updateCategory(id, payload) {
            const current = db.prepare('SELECT * FROM magazine_categories WHERE id = ?').get(id);
            if (!current) return null;
            const slug = uniqueSlugSqlite(
                db,
                'magazine_categories',
                seed.slugify(payload.slug || payload.name || current.slug, current.slug),
                Number(id)
            );
            db.prepare(`
                UPDATE magazine_categories SET name=?, slug=?, parent_id=?, description=?, sort_order=? WHERE id=?
            `).run(
                payload.name != null ? payload.name : current.name,
                slug,
                payload.parentId !== undefined ? (payload.parentId || null) : current.parent_id,
                payload.description != null ? payload.description : current.description,
                payload.sortOrder != null ? Number(payload.sortOrder) : current.sort_order,
                Number(id)
            );
            return mapCategory(db.prepare('SELECT * FROM magazine_categories WHERE id = ?').get(id));
        },
        deleteCategory(id) {
            db.prepare('UPDATE magazine_posts SET category_id = NULL WHERE category_id = ?').run(Number(id));
            db.prepare('UPDATE magazine_categories SET parent_id = NULL WHERE parent_id = ?').run(Number(id));
            return db.prepare('DELETE FROM magazine_categories WHERE id = ?').run(Number(id)).changes > 0;
        },
        listTags() {
            return db.prepare('SELECT * FROM magazine_tags ORDER BY name').all().map(mapTag);
        },
        createTag(payload) {
            const slug = uniqueSlugSqlite(db, 'magazine_tags', seed.slugify(payload.slug || payload.name, 'tag'));
            const info = db.prepare('INSERT INTO magazine_tags (name, slug) VALUES (?, ?)').run(payload.name, slug);
            return mapTag(db.prepare('SELECT * FROM magazine_tags WHERE id = ?').get(info.lastInsertRowid));
        },
        deleteTag(id) {
            return db.prepare('DELETE FROM magazine_tags WHERE id = ?').run(Number(id)).changes > 0;
        },
        listAuthors() {
            return db.prepare('SELECT * FROM magazine_authors ORDER BY last_name, id').all().map(mapAuthor);
        },
        getAuthor(idOrSlug) {
            const asId = Number(idOrSlug);
            const row = Number.isFinite(asId) && String(asId) === String(idOrSlug)
                ? db.prepare('SELECT * FROM magazine_authors WHERE id = ?').get(asId)
                : db.prepare('SELECT * FROM magazine_authors WHERE slug = ?').get(String(idOrSlug));
            if (!row) return null;
            const author = mapAuthor(row);
            author.posts = listPosts({ authorSlug: author.slug });
            return author;
        },
        createAuthor(payload) {
            const slug = uniqueSlugSqlite(db, 'magazine_authors', seed.slugify(payload.slug || `${payload.firstName}-${payload.lastName}`, 'author'));
            const info = db.prepare(`
                INSERT INTO magazine_authors (user_id, first_name, last_name, slug, photo_url, specialty, bio)
                VALUES (?, ?, ?, ?, ?, ?, ?)
            `).run(
                payload.userId || null,
                payload.firstName,
                payload.lastName,
                slug,
                payload.photoUrl || null,
                payload.specialty || '',
                payload.bio || ''
            );
            return mapAuthor(db.prepare('SELECT * FROM magazine_authors WHERE id = ?').get(info.lastInsertRowid));
        },
        updateAuthor(id, payload) {
            const current = this.getAuthor(id);
            if (!current) return null;
            const slug = uniqueSlugSqlite(
                db,
                'magazine_authors',
                seed.slugify(payload.slug || `${payload.firstName || current.firstName}-${payload.lastName || current.lastName}`, current.slug),
                Number(id)
            );
            db.prepare(`
                UPDATE magazine_authors SET user_id=?, first_name=?, last_name=?, slug=?, photo_url=?, specialty=?, bio=?
                WHERE id=?
            `).run(
                payload.userId !== undefined ? payload.userId || null : current.userId,
                payload.firstName != null ? payload.firstName : current.firstName,
                payload.lastName != null ? payload.lastName : current.lastName,
                slug,
                payload.photoUrl != null ? payload.photoUrl : current.photoUrl,
                payload.specialty != null ? payload.specialty : current.specialty,
                payload.bio != null ? payload.bio : current.bio,
                Number(id)
            );
            return mapAuthor(db.prepare('SELECT * FROM magazine_authors WHERE id = ?').get(id));
        },
        deleteAuthor(id) {
            return db.prepare('DELETE FROM magazine_authors WHERE id = ?').run(Number(id)).changes > 0;
        },
        listPosts,
        getPost,
        bumpViews(id) {
            db.prepare('UPDATE magazine_posts SET view_count = view_count + 1 WHERE id = ?').run(Number(id));
        },
        createPost(payload) {
            return savePost(payload, null);
        },
        updatePost(id, payload) {
            const current = getPost(id, { withRelated: false, withComments: false });
            if (!current) return null;
            return savePost(payload, current);
        },
        deletePost(id) {
            return db.prepare('DELETE FROM magazine_posts WHERE id = ?').run(Number(id)).changes > 0;
        },
        listComments,
        listAllComments(status) {
            const rows = status && status !== 'all'
                ? db.prepare(`
                    SELECT c.*, u.first_name, u.last_name, u.is_admin, p.title AS post_title, p.slug AS post_slug
                    FROM magazine_comments c
                    LEFT JOIN users u ON u.id = c.user_id
                    JOIN magazine_posts p ON p.id = c.post_id
                    WHERE c.status = ?
                    ORDER BY c.created_at DESC
                `).all(status)
                : db.prepare(`
                    SELECT c.*, u.first_name, u.last_name, u.is_admin, p.title AS post_title, p.slug AS post_slug
                    FROM magazine_comments c
                    LEFT JOIN users u ON u.id = c.user_id
                    JOIN magazine_posts p ON p.id = c.post_id
                    ORDER BY c.created_at DESC
                `).all();
            return rows.map((row) => ({ ...mapComment(row), postTitle: row.post_title, postSlug: row.post_slug }));
        },
        createComment(postId, payload) {
            const info = db.prepare(`
                INSERT INTO magazine_comments (post_id, parent_id, user_id, author_name, author_email, author_phone, body, status, is_staff, created_at)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            `).run(
                Number(postId),
                payload.parentId || null,
                payload.userId || null,
                payload.authorName || '',
                payload.authorEmail || '',
                payload.authorPhone || '',
                payload.body,
                payload.status || 'pending',
                payload.isStaff ? 1 : 0,
                nowIso()
            );
            return mapComment(db.prepare('SELECT * FROM magazine_comments WHERE id = ?').get(info.lastInsertRowid));
        },
        moderateComment(id, status) {
            const info = db.prepare('UPDATE magazine_comments SET status = ? WHERE id = ?').run(status, Number(id));
            if (!info.changes) return null;
            return mapComment(db.prepare('SELECT * FROM magazine_comments WHERE id = ?').get(id));
        },
        listBanners,
        createBanner(payload) {
            const info = db.prepare(`
                INSERT INTO magazine_banners (placement, title, subtitle, category, image_url, link, sort_order, expires_at, active, created_at)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            `).run(
                payload.placement,
                payload.title || '',
                payload.subtitle || '',
                payload.category || '',
                payload.imageUrl,
                payload.link || '',
                Number(payload.sortOrder || 0),
                payload.expiresAt || null,
                payload.active == null || asBool(payload.active) ? 1 : 0,
                nowIso()
            );
            return mapBanner(db.prepare('SELECT * FROM magazine_banners WHERE id = ?').get(info.lastInsertRowid));
        },
        updateBanner(id, payload) {
            const current = mapBanner(db.prepare('SELECT * FROM magazine_banners WHERE id = ?').get(id));
            if (!current) return null;
            db.prepare(`
                UPDATE magazine_banners SET placement=?, title=?, subtitle=?, category=?, image_url=?, link=?, sort_order=?, expires_at=?, active=?
                WHERE id=?
            `).run(
                payload.placement || current.placement,
                payload.title != null ? payload.title : current.title,
                payload.subtitle != null ? payload.subtitle : current.subtitle,
                payload.category != null ? payload.category : current.category,
                payload.imageUrl != null ? payload.imageUrl : current.imageUrl,
                payload.link != null ? payload.link : current.link,
                payload.sortOrder != null ? Number(payload.sortOrder) : current.sortOrder,
                payload.expiresAt !== undefined ? payload.expiresAt : current.expiresAt,
                payload.active == null ? (current.active ? 1 : 0) : (asBool(payload.active) ? 1 : 0),
                Number(id)
            );
            return mapBanner(db.prepare('SELECT * FROM magazine_banners WHERE id = ?').get(id));
        },
        deleteBanner(id) {
            return db.prepare('DELETE FROM magazine_banners WHERE id = ?').run(Number(id)).changes > 0;
        },
        trackBanner(id, field) {
            if (field !== 'impressions' && field !== 'clicks') return null;
            db.prepare(`UPDATE magazine_banners SET ${field} = ${field} + 1 WHERE id = ?`).run(Number(id));
            return mapBanner(db.prepare('SELECT * FROM magazine_banners WHERE id = ?').get(id));
        },
        home() {
            return {
                hero: listBanners('hero'),
                featured: listPosts({ featured: true, published: true }),
                latestArticles: listPosts({ type: 'article' }).slice(0, 8),
                videos: listPosts({ type: 'video' }).slice(0, 8),
                podcasts: listPosts({ type: 'podcast' }).slice(0, 8),
                categories: buildCategoryTree(listCategoryRows()),
                tags: db.prepare('SELECT * FROM magazine_tags ORDER BY name').all().map(mapTag),
                sidebarBanners: [...listBanners('sidebar-300x250'), ...listBanners('sidebar-300x600')]
            };
        }
    };
}

async function migrateLegacyPg(q, one, many) {
    const count = await one('SELECT COUNT(*)::int AS n FROM magazine_posts');
    if (count && count.n > 0) return;
    const media = ensureMediaFiles();
    const news = await many('SELECT * FROM news ORDER BY id');
    for (let index = 0; index < news.length; index += 1) {
        const item = news[index];
        const mappedSlug = seed.LEGACY_CATEGORY_MAP[item.category] || 'mother-child';
        const category = await one('SELECT id FROM magazine_categories WHERE slug = $1', [mappedSlug]);
        const slug = await uniqueSlugPg(one, 'magazine_posts', seed.slugify(item.title, `article-${item.id}`));
        const content = seed.articleHtml(item.title, item.summary);
        const image = item.image_url || placeholderImage(`magazine-article-${item.id}.svg`, item.title, '#0f766e');
        await q(
            `INSERT INTO magazine_posts (
                id, type, title, slug, summary, content, featured_image_url, category_id,
                view_count, published, featured, featured_order, reading_time_minutes, seo_title, seo_description,
                source_table, source_id, created_at, updated_at, published_at
            ) VALUES ($1,'article',$2,$3,$4,$5,$6,$7,$8,1,$9,$10,$11,$12,$13,'news',$14,$15,$16,$17)`,
            [
                item.id, item.title, slug, item.summary, content, image, category ? category.id : null,
                Math.max(12, 80 - (index * 7)), index < 4 ? 1 : 0, index < 4 ? index + 1 : 0,
                seed.readingTimeMinutes(content, item.summary), `${item.title} | مجله سلامت تات کیدز`,
                item.summary, item.id, item.created_at, item.updated_at || item.created_at, item.created_at
            ]
        );
    }
    const videos = await many('SELECT * FROM videos ORDER BY id');
    const maxNews = news.reduce((max, item) => Math.max(max, Number(item.id) || 0), 0);
    for (let index = 0; index < videos.length; index += 1) {
        const item = videos[index];
        const id = maxNews + index + 1;
        const category = await one('SELECT id FROM magazine_categories WHERE slug = $1', ['education']);
        const slug = await uniqueSlugPg(one, 'magazine_posts', seed.slugify(item.title, `video-${item.id}`));
        const content = seed.videoHtml(item.title);
        const image = item.thumbnail_url || placeholderImage(`magazine-video-${item.id}.svg`, item.title, '#0d9488');
        const embed = seed.toEmbedUrl(item.url);
        await q(
            `INSERT INTO magazine_posts (
                id, type, title, slug, summary, content, featured_image_url, category_id,
                video_url, video_embed_url, captions_url, video_qualities, duration_seconds, view_count,
                published, reading_time_minutes, seo_title, seo_description, source_table, source_id,
                created_at, updated_at, published_at
            ) VALUES ($1,'video',$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,1,$14,$15,$16,'videos',$17,$18,$18,$18)`,
            [
                id, item.title, slug, item.summary, content, image, category ? category.id : null,
                item.url, embed, media.captions,
                JSON.stringify([{ label: 'خودکار', url: embed || item.url }]),
                180 + (index * 25), 40 + (index * 5),
                seed.readingTimeMinutes(content, item.summary), `${item.title} | ویدیو مجله سلامت`,
                item.summary, item.id, item.created_at
            ]
        );
    }
}

function filterHydratedPosts(posts, filters = {}) {
    let list = posts.slice();
    if (filters.published !== false && !filters.includeUnpublished) {
        list = list.filter((post) => post.published);
    }
    if (filters.type) list = list.filter((post) => post.type === filters.type);
    if (filters.featured) list = list.filter((post) => post.featured);
    if (filters.categorySlug) {
        const match = list.find((post) => post.category && post.category.slug === filters.categorySlug);
        const parentId = match && match.category ? match.category.id : null;
        list = list.filter((post) => post.category && (
            post.category.slug === filters.categorySlug || post.category.parentId === parentId
        ));
    }
    if (filters.tagSlug) list = list.filter((post) => (post.tags || []).some((tag) => tag.slug === filters.tagSlug));
    if (filters.authorSlug) list = list.filter((post) => (post.authors || []).some((author) => author.slug === filters.authorSlug));
    if (filters.q) {
        const qtext = String(filters.q).toLowerCase();
        list = list.filter((post) => `${post.title} ${post.summary} ${post.content}`.toLowerCase().includes(qtext));
    }
    if (filters.sort === 'popular') list.sort((a, b) => b.viewCount - a.viewCount);
    else if (filters.featured) list.sort((a, b) => a.featuredOrder - b.featuredOrder);
    else list.sort((a, b) => String(b.createdAt || '').localeCompare(String(a.createdAt || '')));
    return list;
}

function pgApi(q, one, many) {
    async function categoryRows() {
        return many('SELECT * FROM magazine_categories ORDER BY sort_order, id');
    }

    async function hydratePost(row, extras = {}) {
        if (!row) return null;
        const tags = (await many(
            `SELECT t.* FROM magazine_tags t JOIN magazine_post_tags pt ON pt.tag_id = t.id WHERE pt.post_id = $1 ORDER BY t.name`,
            [row.id]
        )).map(mapTag);
        const authors = (await many(
            `SELECT a.* FROM magazine_authors a JOIN magazine_post_authors pa ON pa.author_id = a.id
             WHERE pa.post_id = $1 ORDER BY pa.sort_order, a.id`,
            [row.id]
        )).map(mapAuthor);
        const relatedIds = (await many(
            'SELECT related_post_id AS id FROM magazine_related_posts WHERE post_id = $1 ORDER BY sort_order',
            [row.id]
        )).map((item) => Number(item.id));
        const categories = (await categoryRows()).map(mapCategory);
        const category = categories.find((item) => item.id === Number(row.category_id)) || null;
        const crumbs = [{ name: 'مجله سلامت', slug: '', href: '/news' }];
        if (category) {
            const chain = [];
            let current = category;
            const guard = new Set();
            while (current && !guard.has(current.id)) {
                guard.add(current.id);
                chain.unshift(current);
                current = current.parentId ? categories.find((item) => item.id === current.parentId) : null;
            }
            chain.forEach((item) => crumbs.push({ name: item.name, slug: item.slug, href: `/news/category/${item.slug}` }));
        }
        const related = extras.withRelated === false
            ? []
            : (await Promise.all(relatedIds.map((id) => one(
                `SELECT p.*, c.name AS category_name, c.slug AS category_slug
                 FROM magazine_posts p LEFT JOIN magazine_categories c ON c.id = p.category_id WHERE p.id = $1`,
                [id]
            )))).filter(Boolean).map((item) => mapPost(item));
        let comments;
        if (extras.withComments !== false) comments = await listComments(row.id, { status: 'approved' });
        return mapPost(row, { category, tags, authors, relatedIds, related, comments, breadcrumbs: crumbs });
    }

    async function listComments(postId, { status } = {}) {
        const rows = status && status !== 'all'
            ? await many(
                `SELECT c.*, u.first_name, u.last_name, u.is_admin FROM magazine_comments c
                 LEFT JOIN users u ON u.id = c.user_id WHERE c.post_id = $1 AND c.status = $2 ORDER BY c.created_at, c.id`,
                [postId, status]
            )
            : await many(
                `SELECT c.*, u.first_name, u.last_name, u.is_admin FROM magazine_comments c
                 LEFT JOIN users u ON u.id = c.user_id WHERE c.post_id = $1 ORDER BY c.created_at, c.id`,
                [postId]
            );
        return nestComments(rows.map(mapComment));
    }

    async function listBanners(placement) {
        const now = nowIso();
        const rows = placement && placement !== 'all'
            ? await many(
                `SELECT * FROM magazine_banners WHERE active = 1 AND placement = $1
                 AND (expires_at IS NULL OR expires_at = '' OR expires_at > $2) ORDER BY sort_order, id`,
                [placement, now]
            )
            : await many('SELECT * FROM magazine_banners ORDER BY placement, sort_order, id');
        return rows.map(mapBanner);
    }

    async function listPosts(filters = {}) {
        const rows = await many(`
            SELECT p.*, c.name AS category_name, c.slug AS category_slug
            FROM magazine_posts p
            LEFT JOIN magazine_categories c ON c.id = p.category_id
            ORDER BY p.created_at DESC, p.id DESC
        `);
        const hydrated = [];
        for (const row of rows) hydrated.push(await hydratePost(row, { withRelated: false, withComments: false }));
        return filterHydratedPosts(hydrated, filters);
    }

    async function getPost(idOrSlug) {
        const asId = Number(idOrSlug);
        let row = Number.isFinite(asId) && String(asId) === String(idOrSlug)
            ? await one('SELECT * FROM magazine_posts WHERE id = $1', [asId])
            : await one('SELECT * FROM magazine_posts WHERE slug = $1', [String(idOrSlug)]);
        if (!row && Number.isFinite(asId)) {
            row = await one("SELECT * FROM magazine_posts WHERE source_table = 'news' AND source_id = $1", [asId]);
        }
        return hydratePost(row);
    }

    async function setRelations(postId, payload) {
        if (Array.isArray(payload.tagIds)) {
            await q('DELETE FROM magazine_post_tags WHERE post_id = $1', [postId]);
            for (const tagId of payload.tagIds.map(Number).filter(Boolean)) {
                await q('INSERT INTO magazine_post_tags (post_id, tag_id) VALUES ($1,$2) ON CONFLICT DO NOTHING', [postId, tagId]);
            }
        }
        if (Array.isArray(payload.authorIds)) {
            await q('DELETE FROM magazine_post_authors WHERE post_id = $1', [postId]);
            for (let i = 0; i < payload.authorIds.length; i += 1) {
                const authorId = Number(payload.authorIds[i]);
                if (authorId) {
                    await q('INSERT INTO magazine_post_authors (post_id, author_id, sort_order) VALUES ($1,$2,$3) ON CONFLICT DO NOTHING', [postId, authorId, i]);
                }
            }
        }
        if (Array.isArray(payload.relatedIds)) {
            await q('DELETE FROM magazine_related_posts WHERE post_id = $1', [postId]);
            for (let i = 0; i < payload.relatedIds.length; i += 1) {
                const relatedId = Number(payload.relatedIds[i]);
                if (relatedId && relatedId !== Number(postId)) {
                    await q('INSERT INTO magazine_related_posts (post_id, related_post_id, sort_order) VALUES ($1,$2,$3) ON CONFLICT DO NOTHING', [postId, relatedId, i]);
                }
            }
        }
    }

    async function savePost(payload, existing) {
        const type = payload.type || (existing && existing.type) || 'article';
        const title = payload.title || (existing && existing.title);
        const slug = await uniqueSlugPg(one, 'magazine_posts', seed.slugify(payload.slug || payload.title || (existing && existing.slug), 'post'), existing && existing.id);
        const content = payload.content != null ? payload.content : (existing && existing.content) || '';
        const summary = payload.summary != null ? payload.summary : (existing && existing.summary) || '';
        const durationSeconds = payload.durationSeconds != null
            ? Number(payload.durationSeconds)
            : seed.parseDurationSeconds(payload.duration) || (existing && existing.durationSeconds) || 0;
        const values = [
            type, title, slug, summary, content,
            payload.featuredImageUrl != null ? payload.featuredImageUrl : (existing && existing.featuredImageUrl) || null,
            payload.categoryId != null && payload.categoryId !== '' ? Number(payload.categoryId) : (existing ? existing.categoryId : null),
            payload.videoUrl != null ? payload.videoUrl : (existing && existing.videoUrl) || null,
            payload.videoEmbedUrl != null ? payload.videoEmbedUrl : seed.toEmbedUrl(payload.videoUrl || (existing && existing.videoUrl)),
            payload.videoFileUrl != null ? payload.videoFileUrl : (existing && existing.videoFileUrl) || null,
            payload.captionsUrl != null ? payload.captionsUrl : (existing && existing.captionsUrl) || null,
            payload.videoQualities ? JSON.stringify(payload.videoQualities) : (existing && existing.videoQualities && existing.videoQualities.length ? JSON.stringify(existing.videoQualities) : null),
            payload.audioUrl != null ? payload.audioUrl : (existing && existing.audioUrl) || null,
            payload.audioFileUrl != null ? payload.audioFileUrl : (existing && existing.audioFileUrl) || null,
            payload.transcript != null ? payload.transcript : (existing && existing.transcript) || null,
            durationSeconds,
            payload.published == null ? (existing ? (existing.published ? 1 : 0) : 1) : (asBool(payload.published) ? 1 : 0),
            payload.featured == null ? (existing ? (existing.featured ? 1 : 0) : 0) : (asBool(payload.featured) ? 1 : 0),
            payload.featuredOrder != null ? Number(payload.featuredOrder) : (existing && existing.featuredOrder) || 0,
            seed.readingTimeMinutes(content, summary),
            payload.seoTitle != null ? payload.seoTitle : (existing && existing.seoTitle) || title,
            payload.seoDescription != null ? payload.seoDescription : (existing && existing.seoDescription) || summary,
            nowIso()
        ];
        let id;
        if (existing) {
            id = Number(existing.id);
            await q(
                `UPDATE magazine_posts SET type=$1, title=$2, slug=$3, summary=$4, content=$5, featured_image_url=$6, category_id=$7,
                 video_url=$8, video_embed_url=$9, video_file_url=$10, captions_url=$11, video_qualities=$12,
                 audio_url=$13, audio_file_url=$14, transcript=$15, duration_seconds=$16, published=$17, featured=$18,
                 featured_order=$19, reading_time_minutes=$20, seo_title=$21, seo_description=$22, updated_at=$23 WHERE id=$24`,
                [...values, id]
            );
        } else {
            const created = nowIso();
            const row = await one(
                `INSERT INTO magazine_posts (
                    type, title, slug, summary, content, featured_image_url, category_id,
                    video_url, video_embed_url, video_file_url, captions_url, video_qualities,
                    audio_url, audio_file_url, transcript, duration_seconds, published, featured,
                    featured_order, reading_time_minutes, seo_title, seo_description, updated_at, created_at, published_at
                ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$24)
                RETURNING id`,
                [...values, created]
            );
            id = Number(row.id);
        }
        await setRelations(id, payload);
        return getPost(id);
    }

    return {
        async listCategories() {
            return buildCategoryTree(await categoryRows());
        },
        async flattenCategories() {
            return (await categoryRows()).map(mapCategory);
        },
        async listTags() {
            return (await many('SELECT * FROM magazine_tags ORDER BY name')).map(mapTag);
        },
        async listAuthors() {
            return (await many('SELECT * FROM magazine_authors ORDER BY last_name, id')).map(mapAuthor);
        },
        listPosts,
        getPost,
        async bumpViews(id) {
            await q('UPDATE magazine_posts SET view_count = view_count + 1 WHERE id = $1', [Number(id)]);
        },
        createPost(payload) {
            return savePost(payload, null);
        },
        async updatePost(id, payload) {
            const current = await getPost(id);
            if (!current) return null;
            return savePost(payload, current);
        },
        async deletePost(id) {
            const result = await q('DELETE FROM magazine_posts WHERE id = $1', [Number(id)]);
            return result.rowCount > 0;
        },
        listComments,
        async listAllComments(status) {
            const rows = status && status !== 'all'
                ? await many(
                    `SELECT c.*, u.first_name, u.last_name, u.is_admin, p.title AS post_title, p.slug AS post_slug
                     FROM magazine_comments c LEFT JOIN users u ON u.id = c.user_id
                     JOIN magazine_posts p ON p.id = c.post_id WHERE c.status = $1 ORDER BY c.created_at DESC`,
                    [status]
                )
                : await many(
                    `SELECT c.*, u.first_name, u.last_name, u.is_admin, p.title AS post_title, p.slug AS post_slug
                     FROM magazine_comments c LEFT JOIN users u ON u.id = c.user_id
                     JOIN magazine_posts p ON p.id = c.post_id ORDER BY c.created_at DESC`
                );
            return rows.map((row) => ({ ...mapComment(row), postTitle: row.post_title, postSlug: row.post_slug }));
        },
        async createComment(postId, payload) {
            const row = await one(
                `INSERT INTO magazine_comments (post_id, parent_id, user_id, author_name, author_email, author_phone, body, status, is_staff, created_at)
                 VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,
                [
                    Number(postId), payload.parentId || null, payload.userId || null, payload.authorName || '',
                    payload.authorEmail || '', payload.authorPhone || '', payload.body, payload.status || 'pending',
                    payload.isStaff ? 1 : 0, nowIso()
                ]
            );
            return mapComment(row);
        },
        async moderateComment(id, status) {
            await q('UPDATE magazine_comments SET status = $1 WHERE id = $2', [status, Number(id)]);
            return mapComment(await one('SELECT * FROM magazine_comments WHERE id = $1', [Number(id)]));
        },
        async createCategory(payload) {
            const slug = await uniqueSlugPg(one, 'magazine_categories', seed.slugify(payload.slug || payload.name, 'category'));
            return mapCategory(await one(
                `INSERT INTO magazine_categories (name, slug, parent_id, description, sort_order) VALUES ($1,$2,$3,$4,$5) RETURNING *`,
                [payload.name, slug, payload.parentId || null, payload.description || '', Number(payload.sortOrder || 0)]
            ));
        },
        async updateCategory(id, payload) {
            const current = await one('SELECT * FROM magazine_categories WHERE id = $1', [Number(id)]);
            if (!current) return null;
            const slug = await uniqueSlugPg(one, 'magazine_categories', seed.slugify(payload.slug || payload.name || current.slug, current.slug), Number(id));
            return mapCategory(await one(
                `UPDATE magazine_categories SET name=$1, slug=$2, parent_id=$3, description=$4, sort_order=$5 WHERE id=$6 RETURNING *`,
                [
                    payload.name != null ? payload.name : current.name, slug,
                    payload.parentId !== undefined ? (payload.parentId || null) : current.parent_id,
                    payload.description != null ? payload.description : current.description,
                    payload.sortOrder != null ? Number(payload.sortOrder) : current.sort_order, Number(id)
                ]
            ));
        },
        async deleteCategory(id) {
            await q('UPDATE magazine_posts SET category_id = NULL WHERE category_id = $1', [Number(id)]);
            await q('UPDATE magazine_categories SET parent_id = NULL WHERE parent_id = $1', [Number(id)]);
            const result = await q('DELETE FROM magazine_categories WHERE id = $1', [Number(id)]);
            return result.rowCount > 0;
        },
        async createTag(payload) {
            const slug = await uniqueSlugPg(one, 'magazine_tags', seed.slugify(payload.slug || payload.name, 'tag'));
            return mapTag(await one('INSERT INTO magazine_tags (name, slug) VALUES ($1,$2) RETURNING *', [payload.name, slug]));
        },
        async deleteTag(id) {
            const result = await q('DELETE FROM magazine_tags WHERE id = $1', [Number(id)]);
            return result.rowCount > 0;
        },
        async getAuthor(idOrSlug) {
            const asId = Number(idOrSlug);
            const row = Number.isFinite(asId) && String(asId) === String(idOrSlug)
                ? await one('SELECT * FROM magazine_authors WHERE id = $1', [asId])
                : await one('SELECT * FROM magazine_authors WHERE slug = $1', [String(idOrSlug)]);
            if (!row) return null;
            const author = mapAuthor(row);
            author.posts = await listPosts({ authorSlug: author.slug });
            return author;
        },
        async createAuthor(payload) {
            const slug = await uniqueSlugPg(one, 'magazine_authors', seed.slugify(payload.slug || `${payload.firstName}-${payload.lastName}`, 'author'));
            return mapAuthor(await one(
                `INSERT INTO magazine_authors (user_id, first_name, last_name, slug, photo_url, specialty, bio)
                 VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING *`,
                [payload.userId || null, payload.firstName, payload.lastName, slug, payload.photoUrl || null, payload.specialty || '', payload.bio || '']
            ));
        },
        async updateAuthor(id, payload) {
            const current = mapAuthor(await one('SELECT * FROM magazine_authors WHERE id = $1', [Number(id)]));
            if (!current) return null;
            const slug = await uniqueSlugPg(one, 'magazine_authors', seed.slugify(payload.slug || `${payload.firstName || current.firstName}-${payload.lastName || current.lastName}`, current.slug), Number(id));
            return mapAuthor(await one(
                `UPDATE magazine_authors SET user_id=$1, first_name=$2, last_name=$3, slug=$4, photo_url=$5, specialty=$6, bio=$7 WHERE id=$8 RETURNING *`,
                [
                    payload.userId !== undefined ? payload.userId || null : current.userId,
                    payload.firstName != null ? payload.firstName : current.firstName,
                    payload.lastName != null ? payload.lastName : current.lastName, slug,
                    payload.photoUrl != null ? payload.photoUrl : current.photoUrl,
                    payload.specialty != null ? payload.specialty : current.specialty,
                    payload.bio != null ? payload.bio : current.bio, Number(id)
                ]
            ));
        },
        async deleteAuthor(id) {
            const result = await q('DELETE FROM magazine_authors WHERE id = $1', [Number(id)]);
            return result.rowCount > 0;
        },
        listBanners,
        async createBanner(payload) {
            return mapBanner(await one(
                `INSERT INTO magazine_banners (placement, title, subtitle, category, image_url, link, sort_order, expires_at, active, created_at)
                 VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,
                [
                    payload.placement, payload.title || '', payload.subtitle || '', payload.category || '',
                    payload.imageUrl, payload.link || '', Number(payload.sortOrder || 0), payload.expiresAt || null,
                    payload.active == null || asBool(payload.active) ? 1 : 0, nowIso()
                ]
            ));
        },
        async updateBanner(id, payload) {
            const current = mapBanner(await one('SELECT * FROM magazine_banners WHERE id = $1', [Number(id)]));
            if (!current) return null;
            return mapBanner(await one(
                `UPDATE magazine_banners SET placement=$1, title=$2, subtitle=$3, category=$4, image_url=$5, link=$6, sort_order=$7, expires_at=$8, active=$9
                 WHERE id=$10 RETURNING *`,
                [
                    payload.placement || current.placement,
                    payload.title != null ? payload.title : current.title,
                    payload.subtitle != null ? payload.subtitle : current.subtitle,
                    payload.category != null ? payload.category : current.category,
                    payload.imageUrl != null ? payload.imageUrl : current.imageUrl,
                    payload.link != null ? payload.link : current.link,
                    payload.sortOrder != null ? Number(payload.sortOrder) : current.sortOrder,
                    payload.expiresAt !== undefined ? payload.expiresAt : current.expiresAt,
                    payload.active == null ? (current.active ? 1 : 0) : (asBool(payload.active) ? 1 : 0),
                    Number(id)
                ]
            ));
        },
        async deleteBanner(id) {
            const result = await q('DELETE FROM magazine_banners WHERE id = $1', [Number(id)]);
            return result.rowCount > 0;
        },
        async trackBanner(id, field) {
            if (field !== 'impressions' && field !== 'clicks') return null;
            await q(`UPDATE magazine_banners SET ${field} = ${field} + 1 WHERE id = $1`, [Number(id)]);
            return mapBanner(await one('SELECT * FROM magazine_banners WHERE id = $1', [Number(id)]));
        },
        async home() {
            const categories = buildCategoryTree(await categoryRows());
            const tags = (await many('SELECT * FROM magazine_tags ORDER BY name')).map(mapTag);
            return {
                hero: await listBanners('hero'),
                featured: await listPosts({ featured: true }),
                latestArticles: (await listPosts({ type: 'article' })).slice(0, 8),
                videos: (await listPosts({ type: 'video' })).slice(0, 8),
                podcasts: (await listPosts({ type: 'podcast' })).slice(0, 8),
                categories,
                tags,
                sidebarBanners: [...await listBanners('sidebar-300x250'), ...await listBanners('sidebar-300x600')]
            };
        }
    };
}

function rewriteHeroLinksSqlite(db) {
    const banners = db.prepare("SELECT id, link FROM magazine_banners WHERE link LIKE '/news/%'").all();
    banners.forEach((banner) => {
        const slug = String(banner.link || '').replace(/^\/news\//, '');
        if (!slug || /^\d+$/.test(slug)) return;
        const post = db.prepare('SELECT id FROM magazine_posts WHERE slug = ?').get(slug);
        if (post) {
            db.prepare('UPDATE magazine_banners SET link = ? WHERE id = ?').run(`/news/${post.id}`, banner.id);
        }
    });
}

async function rewriteHeroLinksPg(q, one, many) {
    const banners = await many("SELECT id, link FROM magazine_banners WHERE link LIKE '/news/%'");
    for (const banner of banners) {
        const slug = String(banner.link || '').replace(/^\/news\//, '');
        if (!slug || /^\d+$/.test(slug)) continue;
        const post = await one('SELECT id FROM magazine_posts WHERE slug = $1', [slug]);
        if (post) {
            await q('UPDATE magazine_banners SET link = $1 WHERE id = $2', [`/news/${post.id}`, banner.id]);
        }
    }
}

async function runSqlBatch(q, sql) {
    const statements = String(sql)
        .split(';')
        .map((part) => part.trim())
        .filter((part) => part.length > 0);
    for (const statement of statements) {
        await q(statement);
    }
}

async function widenMagazinePgBigints(q) {
    // Older production tables used INTEGER; news/video ids are Date.now() (ms) and overflow int4.
    const statements = [
        'ALTER TABLE magazine_posts ALTER COLUMN source_id TYPE BIGINT USING source_id::bigint',
        'ALTER TABLE magazine_posts ALTER COLUMN id TYPE BIGINT USING id::bigint',
        'ALTER TABLE magazine_posts ALTER COLUMN category_id TYPE BIGINT USING category_id::bigint',
        'ALTER TABLE magazine_categories ALTER COLUMN id TYPE BIGINT USING id::bigint',
        'ALTER TABLE magazine_categories ALTER COLUMN parent_id TYPE BIGINT USING parent_id::bigint',
        'ALTER TABLE magazine_tags ALTER COLUMN id TYPE BIGINT USING id::bigint',
        'ALTER TABLE magazine_authors ALTER COLUMN id TYPE BIGINT USING id::bigint',
        'ALTER TABLE magazine_authors ALTER COLUMN user_id TYPE BIGINT USING user_id::bigint',
        'ALTER TABLE magazine_post_tags ALTER COLUMN post_id TYPE BIGINT USING post_id::bigint',
        'ALTER TABLE magazine_post_tags ALTER COLUMN tag_id TYPE BIGINT USING tag_id::bigint',
        'ALTER TABLE magazine_post_authors ALTER COLUMN post_id TYPE BIGINT USING post_id::bigint',
        'ALTER TABLE magazine_post_authors ALTER COLUMN author_id TYPE BIGINT USING author_id::bigint',
        'ALTER TABLE magazine_related_posts ALTER COLUMN post_id TYPE BIGINT USING post_id::bigint',
        'ALTER TABLE magazine_related_posts ALTER COLUMN related_post_id TYPE BIGINT USING related_post_id::bigint',
        'ALTER TABLE magazine_comments ALTER COLUMN id TYPE BIGINT USING id::bigint',
        'ALTER TABLE magazine_comments ALTER COLUMN post_id TYPE BIGINT USING post_id::bigint',
        'ALTER TABLE magazine_comments ALTER COLUMN parent_id TYPE BIGINT USING parent_id::bigint',
        'ALTER TABLE magazine_comments ALTER COLUMN user_id TYPE BIGINT USING user_id::bigint',
        'ALTER TABLE magazine_banners ALTER COLUMN id TYPE BIGINT USING id::bigint'
    ];
    for (const statement of statements) {
        try {
            await q(statement);
        } catch (err) {
            console.error('Magazine column widen skipped:', statement, err && err.message);
        }
    }
}

function ensureMagazineSchemaSqlite(db) {
    try {
        db.transaction(() => {
            db.exec(TABLES_SQLITE);
            seedTaxonomySqlite(db);
            migrateLegacySqlite(db);
            rewriteHeroLinksSqlite(db);
        })();
    } catch (err) {
        console.error('Magazine schema init failed; auth and other APIs will still start:', err);
    }
}

async function ensureMagazineSchemaPg(q, one, many) {
    try {
        await runSqlBatch(q, TABLES_PG);
        await widenMagazinePgBigints(q);
        await seedTaxonomyPg(q, one);
        await migrateLegacyPg(q, one, many);
        await rewriteHeroLinksPg(q, one, many);
        await q(
            "SELECT setval(pg_get_serial_sequence('magazine_posts', 'id'), COALESCE((SELECT MAX(id) FROM magazine_posts), 1))"
        );
    } catch (err) {
        console.error('Magazine schema init failed; auth and other APIs will still start:', err);
    }
}

module.exports = {
    TABLES_PG,
    ensureMagazineSchemaSqlite,
    ensureMagazineSchemaPg,
    widenMagazinePgBigints,
    sqliteApi,
    pgApi,
    mapPost,
    toLegacyNews(post) {
        if (!post) return null;
        return {
            id: post.id,
            title: post.title,
            summary: post.summary,
            content: post.content,
            category: post.categoryName || (post.category && post.category.name) || '',
            imageUrl: post.featuredImageUrl || post.imageUrl || '',
            createdAt: post.createdAt,
            updatedAt: post.updatedAt,
            slug: post.slug,
            type: post.type
        };
    },
    toLegacyVideo(post) {
        if (!post) return null;
        return {
            id: post.id,
            title: post.title,
            summary: post.summary,
            url: post.videoFileUrl || post.videoUrl || post.videoEmbedUrl || '',
            thumbnailUrl: post.featuredImageUrl || '',
            createdAt: post.createdAt,
            slug: post.slug,
            type: 'video'
        };
    },
    toLegacyPodcast(post) {
        if (!post) return null;
        return {
            id: post.id,
            title: post.title,
            summary: post.summary,
            url: post.audioFileUrl || post.audioUrl || '',
            thumbnailUrl: post.featuredImageUrl || '',
            duration: post.duration,
            createdAt: post.createdAt,
            slug: post.slug,
            type: 'podcast'
        };
    }
};
