-- PostgreSQL schema for TatKids / Roshdyar.
-- Version 3: server-grade relational database with connection pooling.

CREATE TABLE IF NOT EXISTS schema_meta (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT,
    email TEXT,
    mobile TEXT,
    password TEXT,
    first_name TEXT,
    last_name TEXT,
    birth_date TEXT,
    province TEXT,
    city TEXT,
    is_admin INTEGER NOT NULL DEFAULT 0,
    profile_complete INTEGER NOT NULL DEFAULT 0,
    created_at TEXT,
    extra TEXT
);

CREATE INDEX IF NOT EXISTS idx_users_username_lower ON users (lower(username));
CREATE INDEX IF NOT EXISTS idx_users_email_lower ON users (lower(email));
CREATE INDEX IF NOT EXISTS idx_users_mobile ON users (mobile);
CREATE INDEX IF NOT EXISTS idx_users_is_admin ON users (is_admin);

CREATE TABLE IF NOT EXISTS children (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    first_name TEXT,
    last_name TEXT,
    name TEXT,
    gender TEXT,
    birth_date TEXT,
    avatar TEXT,
    height TEXT,
    weight TEXT,
    blood_type TEXT,
    allergies TEXT,
    special_illnesses TEXT,
    national_id TEXT,
    father_name TEXT,
    birth_weight DOUBLE PRECISION,
    birth_height DOUBLE PRECISION,
    birth_head_circumference DOUBLE PRECISION,
    birth_type TEXT,
    gestational_age INTEGER,
    birth_place TEXT,
    apgar1 INTEGER,
    apgar5 INTEGER,
    vaccine_reminder TEXT,
    extra TEXT
);

CREATE INDEX IF NOT EXISTS idx_children_user_id ON children (user_id);

CREATE TABLE IF NOT EXISTS vaccination_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    child_id BIGINT NOT NULL REFERENCES children(id) ON DELETE CASCADE,
    age_group INTEGER NOT NULL,
    vaccine_name TEXT NOT NULL,
    value TEXT NOT NULL,
    UNIQUE (child_id, age_group, vaccine_name)
);

CREATE INDEX IF NOT EXISTS idx_vaccination_child ON vaccination_records (child_id);

CREATE TABLE IF NOT EXISTS growth_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id TEXT UNIQUE,
    child_id BIGINT NOT NULL REFERENCES children(id) ON DELETE CASCADE,
    date TEXT NOT NULL,
    height DOUBLE PRECISION,
    weight DOUBLE PRECISION,
    head_circumference DOUBLE PRECISION,
    UNIQUE (child_id, date)
);

CREATE INDEX IF NOT EXISTS idx_growth_child_date ON growth_records (child_id, date);

CREATE TABLE IF NOT EXISTS medical_visits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    child_id BIGINT NOT NULL REFERENCES children(id) ON DELETE CASCADE,
    date TEXT,
    doctor_name TEXT,
    reason TEXT,
    summary TEXT,
    description TEXT
);

CREATE INDEX IF NOT EXISTS idx_visits_child ON medical_visits (child_id, date);

CREATE TABLE IF NOT EXISTS medical_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    child_id BIGINT NOT NULL REFERENCES children(id) ON DELETE CASCADE,
    title TEXT,
    date TEXT,
    url TEXT,
    uploaded_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_documents_child ON medical_documents (child_id);

CREATE TABLE IF NOT EXISTS checkups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    child_id BIGINT NOT NULL REFERENCES children(id) ON DELETE CASCADE,
    title TEXT,
    date TEXT,
    parameters TEXT,
    file_url TEXT
);

CREATE INDEX IF NOT EXISTS idx_checkups_child ON checkups (child_id, date);

CREATE TABLE IF NOT EXISTS reminders (
    id TEXT PRIMARY KEY,
    child_id BIGINT NOT NULL REFERENCES children(id) ON DELETE CASCADE,
    title TEXT,
    message TEXT,
    description TEXT,
    date TEXT,
    alarm_at TEXT,
    type TEXT,
    source TEXT,
    category TEXT,
    link TEXT,
    extra TEXT
);

CREATE INDEX IF NOT EXISTS idx_reminders_child ON reminders (child_id);

CREATE TABLE IF NOT EXISTS user_reminders (
    id TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title TEXT,
    description TEXT,
    alarm_at TEXT,
    created_at TEXT,
    notified INTEGER NOT NULL DEFAULT 0,
    type TEXT,
    source TEXT,
    extra TEXT
);

CREATE INDEX IF NOT EXISTS idx_user_reminders_user ON user_reminders (user_id, alarm_at);

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    body TEXT,
    link TEXT,
    image_url TEXT,
    type TEXT,
    is_bulk INTEGER NOT NULL DEFAULT 0,
    created_at TEXT,
    created_by BIGINT
);

CREATE INDEX IF NOT EXISTS idx_messages_created ON messages (created_at);

CREATE TABLE IF NOT EXISTS message_recipients (
    message_id BIGINT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    is_read INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (message_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_message_recipients_user ON message_recipients (user_id, is_read);

CREATE TABLE IF NOT EXISTS banners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    link TEXT,
    image_url TEXT
);

CREATE TABLE IF NOT EXISTS news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    summary TEXT,
    content TEXT,
    category TEXT,
    image_url TEXT,
    created_at TEXT,
    updated_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_news_created ON news (created_at);

CREATE TABLE IF NOT EXISTS videos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    summary TEXT,
    url TEXT,
    thumbnail_url TEXT,
    created_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_videos_created ON videos (created_at);

CREATE TABLE IF NOT EXISTS podcasts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    summary TEXT,
    url TEXT,
    thumbnail_url TEXT,
    duration TEXT,
    created_at TEXT
);

CREATE TABLE IF NOT EXISTS tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'open',
    created_at TEXT,
    updated_at TEXT,
    payload TEXT NOT NULL DEFAULT '{}'
);

CREATE INDEX IF NOT EXISTS idx_tickets_status ON tickets (status);
CREATE INDEX IF NOT EXISTS idx_tickets_user ON tickets (user_id, created_at);

CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    category TEXT,
    price DOUBLE PRECISION NOT NULL DEFAULT 0,
    stock INTEGER NOT NULL DEFAULT 0,
    image_url TEXT,
    active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT,
    updated_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_products_active_category ON products (active, category);
CREATE INDEX IF NOT EXISTS idx_products_name ON products (name);

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    total DOUBLE PRECISION NOT NULL DEFAULT 0,
    shipping_address TEXT,
    phone TEXT,
    notes TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    created_at TEXT,
    updated_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_orders_user_created ON orders (user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders (status);

CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id BIGINT,
    name TEXT,
    price DOUBLE PRECISION,
    quantity INTEGER,
    line_total DOUBLE PRECISION
);

CREATE INDEX IF NOT EXISTS idx_order_items_order ON order_items (order_id);

CREATE TABLE IF NOT EXISTS otp_codes (
    phone TEXT PRIMARY KEY,
    code TEXT NOT NULL,
    purpose TEXT NOT NULL,
    expires_at BIGINT NOT NULL,
    sent_at BIGINT NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_otp_expires ON otp_codes (expires_at);

CREATE TABLE IF NOT EXISTS product_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    parent_id BIGINT REFERENCES product_categories(id) ON DELETE CASCADE,
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS product_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    body TEXT NOT NULL,
    created_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_product_images_product ON product_images (product_id);
CREATE INDEX IF NOT EXISTS idx_product_comments_product ON product_comments (product_id, created_at);
CREATE INDEX IF NOT EXISTS idx_product_categories_parent ON product_categories (parent_id);
