const {
    AGE_BANDS,
    SKILLS,
    INTERNAL_VENDOR,
    CATEGORY_DEFAULTS,
    buildCatalogSql,
    mapCatalogRow
} = require('./shop-model');

const SHOP_TABLES_SQLITE = `
CREATE TABLE IF NOT EXISTS shop_vendors (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    slug TEXT UNIQUE NOT NULL,
    display_name TEXT NOT NULL,
    kind TEXT NOT NULL DEFAULT 'internal',
    status TEXT NOT NULL DEFAULT 'active',
    commission_pct REAL NOT NULL DEFAULT 0,
    settlement_cycle TEXT NOT NULL DEFAULT 'weekly',
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS shop_offers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    product_id INTEGER NOT NULL,
    vendor_id INTEGER NOT NULL,
    price REAL NOT NULL,
    compare_at_price REAL,
    stock INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'active',
    sku TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    UNIQUE(product_id, vendor_id),
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    FOREIGN KEY (vendor_id) REFERENCES shop_vendors(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS shop_skills (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    slug TEXT UNIQUE NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS shop_product_meta (
    product_id INTEGER PRIMARY KEY,
    age_band TEXT,
    brand TEXT,
    safety_warning TEXT,
    video_url TEXT,
    weight_g INTEGER,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS shop_product_skills (
    product_id INTEGER NOT NULL,
    skill_id INTEGER NOT NULL,
    impact INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (product_id, skill_id),
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    FOREIGN KEY (skill_id) REFERENCES shop_skills(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS shop_campaigns (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    kind TEXT NOT NULL DEFAULT 'percent',
    value REAL NOT NULL DEFAULT 0,
    starts_at TEXT,
    ends_at TEXT,
    active INTEGER NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_shop_offers_product ON shop_offers(product_id, status);
CREATE INDEX IF NOT EXISTS idx_shop_product_skills_skill ON shop_product_skills(skill_id);
`;

const SHOP_TABLES_PG = `
CREATE TABLE IF NOT EXISTS shop_vendors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT UNIQUE NOT NULL,
    display_name TEXT NOT NULL,
    kind TEXT NOT NULL DEFAULT 'internal',
    status TEXT NOT NULL DEFAULT 'active',
    commission_pct DOUBLE PRECISION NOT NULL DEFAULT 0,
    settlement_cycle TEXT NOT NULL DEFAULT 'weekly',
    created_at TEXT NOT NULL DEFAULT to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

CREATE TABLE IF NOT EXISTS shop_offers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    vendor_id BIGINT NOT NULL REFERENCES shop_vendors(id) ON DELETE CASCADE,
    price DOUBLE PRECISION NOT NULL,
    compare_at_price DOUBLE PRECISION,
    stock INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'active',
    sku TEXT,
    created_at TEXT NOT NULL DEFAULT to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    UNIQUE(product_id, vendor_id)
);

CREATE TABLE IF NOT EXISTS shop_skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT UNIQUE NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS shop_product_meta (
    product_id BIGINT PRIMARY KEY REFERENCES products(id) ON DELETE CASCADE,
    age_band TEXT,
    brand TEXT,
    safety_warning TEXT,
    video_url TEXT,
    weight_g INTEGER
);

CREATE TABLE IF NOT EXISTS shop_product_skills (
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    skill_id BIGINT NOT NULL REFERENCES shop_skills(id) ON DELETE CASCADE,
    impact INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (product_id, skill_id)
);

CREATE TABLE IF NOT EXISTS shop_campaigns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    kind TEXT NOT NULL DEFAULT 'percent',
    value DOUBLE PRECISION NOT NULL DEFAULT 0,
    starts_at TEXT,
    ends_at TEXT,
    active INTEGER NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_shop_offers_product ON shop_offers (product_id, status);
CREATE INDEX IF NOT EXISTS idx_shop_product_skills_skill ON shop_product_skills (skill_id);
`;

function sqliteHasColumn(db, table, column) {
    return db.prepare(`PRAGMA table_info(${table})`).all().some((col) => col.name === column);
}

function mapSkillRow(row) {
    return {
        id: Number(row.id),
        slug: row.slug,
        title: row.title,
        description: row.description || '',
        sortOrder: Number(row.sort_order || 0)
    };
}

function mapVendorRow(row) {
    if (!row) return null;
    return {
        id: Number(row.id),
        slug: row.slug,
        displayName: row.display_name,
        kind: row.kind,
        status: row.status,
        commissionPct: Number(row.commission_pct || 0),
        settlementCycle: row.settlement_cycle
    };
}

function attachSkillsToProducts(products, skillRows) {
    const byPid = new Map();
    skillRows.forEach((row) => {
        const pid = Number(row.product_id);
        if (!byPid.has(pid)) byPid.set(pid, []);
        byPid.get(pid).push({
            id: Number(row.id),
            slug: row.slug,
            title: row.title,
            impact: Number(row.impact || 1)
        });
    });
    return products.map((product) => ({
        ...product,
        skills: byPid.get(product.id) || product.skills || []
    }));
}

function seedDefaultsSqlite(db) {
    const vendor = db.prepare('SELECT * FROM shop_vendors WHERE slug = ?').get(INTERNAL_VENDOR.slug);
    if (!vendor) {
        db.prepare(`
            INSERT INTO shop_vendors (slug, display_name, kind, status, commission_pct, settlement_cycle)
            VALUES (?, ?, ?, ?, ?, ?)
        `).run(
            INTERNAL_VENDOR.slug,
            INTERNAL_VENDOR.displayName,
            INTERNAL_VENDOR.kind,
            INTERNAL_VENDOR.status,
            INTERNAL_VENDOR.commissionPct,
            INTERNAL_VENDOR.settlementCycle
        );
    }
    const insertSkill = db.prepare(
        'INSERT OR IGNORE INTO shop_skills (slug, title, description, sort_order) VALUES (?, ?, ?, ?)'
    );
    SKILLS.forEach((skill, index) => {
        insertSkill.run(skill.slug, skill.title, skill.description, index);
    });
}

function backfillSqlite(db) {
    const vendor = db.prepare('SELECT * FROM shop_vendors WHERE slug = ?').get(INTERNAL_VENDOR.slug);
    if (!vendor) return;
    db.prepare(`
        INSERT INTO shop_offers (product_id, vendor_id, price, stock, status)
        SELECT p.id, ?, p.price, p.stock, 'active'
        FROM products p
        WHERE NOT EXISTS (
            SELECT 1 FROM shop_offers o WHERE o.product_id = p.id AND o.vendor_id = ?
        )
    `).run(vendor.id, vendor.id);

    const products = db.prepare('SELECT id, category FROM products').all();
    const skillBySlug = new Map(
        db.prepare('SELECT * FROM shop_skills').all().map((row) => [row.slug, row])
    );
    const insertMeta = db.prepare(`
        INSERT OR IGNORE INTO shop_product_meta (product_id, age_band)
        VALUES (?, ?)
    `);
    const insertSkill = db.prepare(`
        INSERT OR IGNORE INTO shop_product_skills (product_id, skill_id, impact)
        VALUES (?, ?, 1)
    `);
    products.forEach((product) => {
        const defaults = CATEGORY_DEFAULTS[product.category] || { ageBand: '1-3', skills: ['cognitive'] };
        insertMeta.run(product.id, defaults.ageBand);
        defaults.skills.forEach((slug) => {
            const skill = skillBySlug.get(slug);
            if (skill) insertSkill.run(product.id, skill.id);
        });
    });
}

function ensureShopSchemaSqlite(db) {
    db.exec(SHOP_TABLES_SQLITE);
    if (!sqliteHasColumn(db, 'product_comments', 'rating')) {
        db.exec('ALTER TABLE product_comments ADD COLUMN rating INTEGER');
    }
    if (!sqliteHasColumn(db, 'product_categories', 'active')) {
        db.exec('ALTER TABLE product_categories ADD COLUMN active INTEGER NOT NULL DEFAULT 1');
    }
    seedDefaultsSqlite(db);
    backfillSqlite(db);
}

function listSkillsSqlite(db) {
    return db.prepare('SELECT * FROM shop_skills ORDER BY sort_order, id').all().map(mapSkillRow);
}

function getInternalVendorSqlite(db) {
    return mapVendorRow(db.prepare('SELECT * FROM shop_vendors WHERE slug = ?').get(INTERNAL_VENDOR.slug));
}

function loadSkillsForProductsSqlite(db, products) {
    if (!products.length) return products;
    const ids = products.map((p) => p.id);
    const placeholders = ids.map(() => '?').join(',');
    const rows = db.prepare(`
        SELECT ps.product_id, ps.impact, s.id, s.slug, s.title
        FROM shop_product_skills ps
        JOIN shop_skills s ON s.id = ps.skill_id
        WHERE ps.product_id IN (${placeholders})
    `).all(...ids);
    return attachSkillsToProducts(products, rows);
}

function listCatalogSqlite(db, asBool, filters, options) {
    const { sql, params } = buildCatalogSql(filters, options);
    const rows = db.prepare(sql).all(...params).map((row) => mapCatalogRow(row, asBool));
    return loadSkillsForProductsSqlite(db, rows);
}

function enrichProductSqlite(db, asBool, product) {
    if (!product) return null;
    const rows = listCatalogSqlite(db, asBool, {}, { activeOnly: false }).filter((row) => row.id === product.id);
    const catalog = rows[0] || product;
    return {
        ...product,
        ...catalog,
        images: product.images,
        comments: product.comments
    };
}

function syncProductCommerceSqlite(db, productId, extra = {}) {
    const product = db.prepare('SELECT * FROM products WHERE id = ?').get(Number(productId));
    if (!product) return;
    const vendor = db.prepare('SELECT * FROM shop_vendors WHERE slug = ?').get(INTERNAL_VENDOR.slug);
    if (!vendor) return;
    const price = extra.price != null ? Number(extra.price) : Number(product.price);
    const stock = extra.stock != null ? Number(extra.stock) : Number(product.stock);
    const compareAt = extra.compareAtPrice != null && extra.compareAtPrice !== ''
        ? Number(extra.compareAtPrice)
        : null;
    const existing = db.prepare(
        'SELECT id FROM shop_offers WHERE product_id = ? AND vendor_id = ?'
    ).get(product.id, vendor.id);
    if (existing) {
        db.prepare(`
            UPDATE shop_offers
            SET price = ?, compare_at_price = ?, stock = ?, status = 'active'
            WHERE id = ?
        `).run(price, Number.isFinite(compareAt) ? compareAt : null, stock, existing.id);
    } else {
        db.prepare(`
            INSERT INTO shop_offers (product_id, vendor_id, price, compare_at_price, stock, status)
            VALUES (?, ?, ?, ?, ?, 'active')
        `).run(product.id, vendor.id, price, Number.isFinite(compareAt) ? compareAt : null, stock);
    }

    const ageBand = extra.ageBand || CATEGORY_DEFAULTS[product.category]?.ageBand || null;
    const brand = extra.brand != null ? String(extra.brand).trim() : '';
    const safetyWarning = extra.safetyWarning != null ? String(extra.safetyWarning).trim() : '';
    db.prepare(`
        INSERT INTO shop_product_meta (product_id, age_band, brand, safety_warning)
        VALUES (?, ?, ?, ?)
        ON CONFLICT(product_id) DO UPDATE SET
            age_band = excluded.age_band,
            brand = excluded.brand,
            safety_warning = excluded.safety_warning
    `).run(product.id, ageBand, brand || null, safetyWarning || null);

    if (Array.isArray(extra.skillIds) || Array.isArray(extra.skillSlugs)) {
        db.prepare('DELETE FROM shop_product_skills WHERE product_id = ?').run(product.id);
        const ids = Array.isArray(extra.skillIds)
            ? extra.skillIds.map(Number).filter(Boolean)
            : [];
        const slugs = Array.isArray(extra.skillSlugs) ? extra.skillSlugs : [];
        slugs.forEach((slug) => {
            const skill = db.prepare('SELECT id FROM shop_skills WHERE slug = ?').get(slug);
            if (skill) ids.push(Number(skill.id));
        });
        const insert = db.prepare(
            'INSERT OR IGNORE INTO shop_product_skills (product_id, skill_id, impact) VALUES (?, ?, 1)'
        );
        [...new Set(ids)].forEach((skillId) => insert.run(product.id, skillId));
    }
}

function adjustOfferStockSqlite(db, productId, delta) {
    db.prepare(`
        UPDATE shop_offers SET stock = MAX(0, stock + ?)
        WHERE product_id = ? AND status = 'active'
    `).run(Number(delta), Number(productId));
}

async function ensureShopSchemaPg(q, one, many) {
    await q(SHOP_TABLES_PG);
    await q('ALTER TABLE product_comments ADD COLUMN IF NOT EXISTS rating INTEGER');
    await q('ALTER TABLE product_categories ADD COLUMN IF NOT EXISTS active INTEGER NOT NULL DEFAULT 1');

    const vendor = await one('SELECT * FROM shop_vendors WHERE slug = $1', [INTERNAL_VENDOR.slug]);
    if (!vendor) {
        await q(
            `INSERT INTO shop_vendors (slug, display_name, kind, status, commission_pct, settlement_cycle)
             VALUES ($1,$2,$3,$4,$5,$6)`,
            [
                INTERNAL_VENDOR.slug,
                INTERNAL_VENDOR.displayName,
                INTERNAL_VENDOR.kind,
                INTERNAL_VENDOR.status,
                INTERNAL_VENDOR.commissionPct,
                INTERNAL_VENDOR.settlementCycle
            ]
        );
    }
    for (let i = 0; i < SKILLS.length; i += 1) {
        const skill = SKILLS[i];
        await q(
            `INSERT INTO shop_skills (slug, title, description, sort_order)
             VALUES ($1,$2,$3,$4)
             ON CONFLICT (slug) DO NOTHING`,
            [skill.slug, skill.title, skill.description, i]
        );
    }

    const internal = await one('SELECT * FROM shop_vendors WHERE slug = $1', [INTERNAL_VENDOR.slug]);
    if (internal) {
        await q(
            `INSERT INTO shop_offers (product_id, vendor_id, price, stock, status)
             SELECT p.id, $1, p.price, p.stock, 'active'
             FROM products p
             WHERE NOT EXISTS (
                SELECT 1 FROM shop_offers o WHERE o.product_id = p.id AND o.vendor_id = $1
             )`,
            [internal.id]
        );
    }

    const products = await many('SELECT id, category FROM products');
    const skillRows = await many('SELECT * FROM shop_skills');
    const skillBySlug = new Map(skillRows.map((row) => [row.slug, row]));
    for (const product of products) {
        const defaults = CATEGORY_DEFAULTS[product.category] || { ageBand: '1-3', skills: ['cognitive'] };
        await q(
            `INSERT INTO shop_product_meta (product_id, age_band)
             VALUES ($1,$2)
             ON CONFLICT (product_id) DO NOTHING`,
            [product.id, defaults.ageBand]
        );
        for (const slug of defaults.skills) {
            const skill = skillBySlug.get(slug);
            if (skill) {
                await q(
                    `INSERT INTO shop_product_skills (product_id, skill_id, impact)
                     VALUES ($1,$2,1)
                     ON CONFLICT (product_id, skill_id) DO NOTHING`,
                    [product.id, skill.id]
                );
            }
        }
    }
}

function toPg(sql) {
    let index = 0;
    return String(sql).replace(/\?/g, () => `$${++index}`);
}

async function listSkillsPg(many) {
    return (await many('SELECT * FROM shop_skills ORDER BY sort_order, id')).map(mapSkillRow);
}

async function getInternalVendorPg(one) {
    return mapVendorRow(await one('SELECT * FROM shop_vendors WHERE slug = $1', [INTERNAL_VENDOR.slug]));
}

async function loadSkillsForProductsPg(many, products) {
    if (!products.length) return products;
    const ids = products.map((p) => p.id);
    const rows = await many(`
        SELECT ps.product_id, ps.impact, s.id, s.slug, s.title
        FROM shop_product_skills ps
        JOIN shop_skills s ON s.id = ps.skill_id
        WHERE ps.product_id = ANY($1::bigint[])
    `, [ids]);
    return attachSkillsToProducts(products, rows);
}

async function listCatalogPg(many, asBool, filters, options) {
    const { sql, params } = buildCatalogSql(filters, options);
    const rows = (await many(toPg(sql), params)).map((row) => mapCatalogRow(row, asBool));
    return loadSkillsForProductsPg(many, rows);
}

async function enrichProductPg(many, asBool, product) {
    if (!product) return null;
    const rows = await listCatalogPg(many, asBool, {}, { activeOnly: false });
    const catalog = rows.find((row) => row.id === product.id) || product;
    return {
        ...product,
        ...catalog,
        images: product.images,
        comments: product.comments
    };
}

async function syncProductCommercePg(q, one, productId, extra = {}) {
    const product = await one('SELECT * FROM products WHERE id = $1', [Number(productId)]);
    if (!product) return;
    const vendor = await one('SELECT * FROM shop_vendors WHERE slug = $1', [INTERNAL_VENDOR.slug]);
    if (!vendor) return;
    const price = extra.price != null ? Number(extra.price) : Number(product.price);
    const stock = extra.stock != null ? Number(extra.stock) : Number(product.stock);
    const compareAt = extra.compareAtPrice != null && extra.compareAtPrice !== ''
        ? Number(extra.compareAtPrice)
        : null;
    await q(
        `INSERT INTO shop_offers (product_id, vendor_id, price, compare_at_price, stock, status)
         VALUES ($1,$2,$3,$4,$5,'active')
         ON CONFLICT (product_id, vendor_id) DO UPDATE SET
            price = EXCLUDED.price,
            compare_at_price = EXCLUDED.compare_at_price,
            stock = EXCLUDED.stock,
            status = 'active'`,
        [product.id, vendor.id, price, Number.isFinite(compareAt) ? compareAt : null, stock]
    );
    const ageBand = extra.ageBand || CATEGORY_DEFAULTS[product.category]?.ageBand || null;
    const brand = extra.brand != null ? String(extra.brand).trim() : '';
    const safetyWarning = extra.safetyWarning != null ? String(extra.safetyWarning).trim() : '';
    await q(
        `INSERT INTO shop_product_meta (product_id, age_band, brand, safety_warning)
         VALUES ($1,$2,$3,$4)
         ON CONFLICT (product_id) DO UPDATE SET
            age_band = EXCLUDED.age_band,
            brand = EXCLUDED.brand,
            safety_warning = EXCLUDED.safety_warning`,
        [product.id, ageBand, brand || null, safetyWarning || null]
    );
    if (Array.isArray(extra.skillIds) || Array.isArray(extra.skillSlugs)) {
        await q('DELETE FROM shop_product_skills WHERE product_id = $1', [product.id]);
        const ids = Array.isArray(extra.skillIds)
            ? extra.skillIds.map(Number).filter(Boolean)
            : [];
        const slugs = Array.isArray(extra.skillSlugs) ? extra.skillSlugs : [];
        for (const slug of slugs) {
            const skill = await one('SELECT id FROM shop_skills WHERE slug = $1', [slug]);
            if (skill) ids.push(Number(skill.id));
        }
        for (const skillId of [...new Set(ids)]) {
            await q(
                `INSERT INTO shop_product_skills (product_id, skill_id, impact)
                 VALUES ($1,$2,1)
                 ON CONFLICT (product_id, skill_id) DO NOTHING`,
                [product.id, skillId]
            );
        }
    }
}

async function adjustOfferStockPg(q, productId, delta, client) {
    await q(
        `UPDATE shop_offers SET stock = GREATEST(0, stock + $1)
         WHERE product_id = $2 AND status = 'active'`,
        [Number(delta), Number(productId)],
        client
    );
}

module.exports = {
    AGE_BANDS,
    SKILLS,
    INTERNAL_VENDOR,
    ensureShopSchemaSqlite,
    listSkillsSqlite,
    getInternalVendorSqlite,
    listCatalogSqlite,
    enrichProductSqlite,
    syncProductCommerceSqlite,
    adjustOfferStockSqlite,
    ensureShopSchemaPg,
    listSkillsPg,
    getInternalVendorPg,
    listCatalogPg,
    enrichProductPg,
    syncProductCommercePg,
    adjustOfferStockPg
};
