const {
    AGE_BANDS,
    SKILLS,
    INTERNAL_VENDOR,
    CATEGORY_DEFAULTS,
    buildCategoryTree,
    descendantCategoryNames,
    buildCatalogSql,
    mapCatalogRow
} = require('./shop-model');

const SHOP_TABLES_SQLITE = `
CREATE TABLE IF NOT EXISTS shop_vendors (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    slug TEXT UNIQUE NOT NULL,
    display_name TEXT NOT NULL,
    kind TEXT NOT NULL DEFAULT 'internal',
    status TEXT NOT NULL DEFAULT 'active',
    commission_pct REAL NOT NULL DEFAULT 0,
    settlement_cycle TEXT NOT NULL DEFAULT 'weekly',
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS shop_offers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    product_id INTEGER NOT NULL,
    vendor_id INTEGER NOT NULL,
    price REAL NOT NULL,
    compare_at_price REAL,
    stock INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'active',
    sku TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    UNIQUE(product_id, vendor_id),
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    FOREIGN KEY (vendor_id) REFERENCES shop_vendors(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS shop_skills (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    slug TEXT UNIQUE NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS shop_product_meta (
    product_id INTEGER PRIMARY KEY,
    age_band TEXT,
    brand TEXT,
    safety_warning TEXT,
    video_url TEXT,
    weight_g INTEGER,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS shop_product_skills (
    product_id INTEGER NOT NULL,
    skill_id INTEGER NOT NULL,
    impact INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (product_id, skill_id),
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    FOREIGN KEY (skill_id) REFERENCES shop_skills(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS shop_campaigns (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    kind TEXT NOT NULL DEFAULT 'percent',
    value REAL NOT NULL DEFAULT 0,
    starts_at TEXT,
    ends_at TEXT,
    active INTEGER NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_shop_offers_product ON shop_offers(product_id, status);
CREATE INDEX IF NOT EXISTS idx_shop_product_skills_skill ON shop_product_skills(skill_id);
`;

const SHOP_TABLES_PG = `
CREATE TABLE IF NOT EXISTS shop_vendors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT UNIQUE NOT NULL,
    display_name TEXT NOT NULL,
    kind TEXT NOT NULL DEFAULT 'internal',
    status TEXT NOT NULL DEFAULT 'active',
    commission_pct DOUBLE PRECISION NOT NULL DEFAULT 0,
    settlement_cycle TEXT NOT NULL DEFAULT 'weekly',
    created_at TEXT NOT NULL DEFAULT to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

CREATE TABLE IF NOT EXISTS shop_offers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    vendor_id BIGINT NOT NULL REFERENCES shop_vendors(id) ON DELETE CASCADE,
    price DOUBLE PRECISION NOT NULL,
    compare_at_price DOUBLE PRECISION,
    stock INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'active',
    sku TEXT,
    created_at TEXT NOT NULL DEFAULT to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    UNIQUE(product_id, vendor_id)
);

CREATE TABLE IF NOT EXISTS shop_skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT UNIQUE NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS shop_product_meta (
    product_id BIGINT PRIMARY KEY REFERENCES products(id) ON DELETE CASCADE,
    age_band TEXT,
    brand TEXT,
    safety_warning TEXT,
    video_url TEXT,
    weight_g INTEGER
);

CREATE TABLE IF NOT EXISTS shop_product_skills (
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    skill_id BIGINT NOT NULL REFERENCES shop_skills(id) ON DELETE CASCADE,
    impact INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (product_id, skill_id)
);

CREATE TABLE IF NOT EXISTS shop_campaigns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    kind TEXT NOT NULL DEFAULT 'percent',
    value DOUBLE PRECISION NOT NULL DEFAULT 0,
    starts_at TEXT,
    ends_at TEXT,
    active INTEGER NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_shop_offers_product ON shop_offers (product_id, status);
CREATE INDEX IF NOT EXISTS idx_shop_product_skills_skill ON shop_product_skills (skill_id);
`;

function sqliteHasColumn(db, table, column) {
    return db.prepare(`PRAGMA table_info(${table})`).all().some((col) => col.name === column);
}

function mapSkillRow(row) {
    return {
        id: Number(row.id),
        slug: row.slug,
        title: row.title,
        description: row.description || '',
        sortOrder: Number(row.sort_order || 0)
    };
}

function mapVendorRow(row) {
    if (!row) return null;
    return {
        id: Number(row.id),
        slug: row.slug,
        displayName: row.display_name,
        kind: row.kind,
        status: row.status,
        commissionPct: Number(row.commission_pct || 0),
        settlementCycle: row.settlement_cycle,
        userId: row.user_id != null ? Number(row.user_id) : null,
        phone: row.phone || '',
        docsNote: row.docs_note || ''
    };
}

function slugifyVendor(name) {
    const base = String(name || 'vendor')
        .trim()
        .toLowerCase()
        .replace(/\s+/g, '-')
        .replace(/[^a-z0-9\u0600-\u06ff-]/g, '')
        .slice(0, 40) || 'vendor';
    return `${base}-${Date.now().toString(36)}`;
}

function seedShopExtrasSqlite(db) {
    ['user_id', 'phone', 'docs_note'].forEach((col) => {
        const type = col === 'user_id' ? 'INTEGER' : 'TEXT';
        if (!sqliteHasColumn(db, 'shop_vendors', col)) {
            db.exec(`ALTER TABLE shop_vendors ADD COLUMN ${col} ${type}`);
        }
    });
    ['placement', 'subtitle'].forEach((col) => {
        if (!sqliteHasColumn(db, 'banners', col)) {
            db.exec(`ALTER TABLE banners ADD COLUMN ${col} TEXT`);
        }
    });
    if (!sqliteHasColumn(db, 'banners', 'product_id')) {
        db.exec('ALTER TABLE banners ADD COLUMN product_id INTEGER');
    }
    if (!sqliteHasColumn(db, 'banners', 'sort_order')) {
        db.exec('ALTER TABLE banners ADD COLUMN sort_order INTEGER NOT NULL DEFAULT 0');
    }
    db.prepare("UPDATE banners SET placement = 'home' WHERE placement IS NULL OR placement = ''").run();

    const campaign = db.prepare('SELECT * FROM shop_campaigns WHERE active = 1 ORDER BY id DESC LIMIT 1').get();
    const now = Date.now();
    if (!campaign || (campaign.ends_at && new Date(campaign.ends_at).getTime() < now)) {
        const ends = new Date(now + 3 * 24 * 60 * 60 * 1000).toISOString();
        db.prepare(`
            INSERT INTO shop_campaigns (title, kind, value, starts_at, ends_at, active)
            VALUES (?, 'percent', 20, ?, ?, 1)
        `).run('فروش ویژه', new Date(now).toISOString(), ends);
    }

    const saleCount = db.prepare(
        'SELECT COUNT(*) AS n FROM shop_offers WHERE compare_at_price IS NOT NULL AND compare_at_price > price'
    ).get().n;
    if (saleCount === 0) {
        db.prepare(`
            UPDATE shop_offers
            SET compare_at_price = CAST(price * 1.35 AS INTEGER)
            WHERE id IN (SELECT id FROM shop_offers ORDER BY id LIMIT 4)
        `).run();
    }

    seedCategoryTreeSqlite(db);
}

const CATEGORY_TREE_SEED = {
    'اسباب‌بازی': [
        { name: 'دخترانه', children: ['عروسک', 'آشپزخانه'] },
        { name: 'پسرانه', children: ['لگو', 'ماشین', 'تفنگ'] },
        { name: 'ساختنی' },
        { name: 'چوبی' },
        { name: 'حرکتی' }
    ],
    'کتاب': [{ name: 'داستان' }, { name: 'آموزشی' }],
    'تغذیه': [{ name: 'غذای کمکی' }, { name: 'میان‌وعده' }],
    'پوشاک': [{ name: 'نوزاد' }, { name: 'کودک' }],
    'بهداشت': [{ name: 'حمام' }, { name: 'مراقبت پوست' }]
};

function looksLikePhone(value) {
    const digits = String(value || '').replace(/[\s-]/g, '');
    return /^\+?\d{8,15}$/.test(digits);
}

function publicCommentAuthor(row) {
    const username = String((row && row.username) || '').trim();
    if (username && !looksLikePhone(username)) return username;
    return 'کاربر تات کیدز';
}

function seedCategoryTreeSqlite(db) {
    const find = (name, parentId) => (parentId == null
        ? db.prepare('SELECT * FROM product_categories WHERE name = ? AND parent_id IS NULL').get(name)
        : db.prepare('SELECT * FROM product_categories WHERE name = ? AND parent_id = ?').get(name, parentId));
    const insert = db.prepare('INSERT INTO product_categories (name, parent_id, sort_order) VALUES (?, ?, ?)');
    const ensure = (name, parentId, sort) => {
        const row = find(name, parentId);
        if (row) return row;
        const info = insert.run(name, parentId, sort);
        return { id: Number(info.lastInsertRowid), name };
    };
    Object.entries(CATEGORY_TREE_SEED).forEach(([rootName, children]) => {
        const root = find(rootName, null);
        if (!root) return;
        children.forEach((child, index) => {
            const node = ensure(child.name, root.id, index);
            (child.children || []).forEach((leaf, leafIndex) => ensure(leaf, node.id, leafIndex));
        });
    });
}

async function seedCategoryTreePg(one, q) {
    const find = async (name, parentId) => (parentId == null
        ? one('SELECT * FROM product_categories WHERE name = $1 AND parent_id IS NULL', [name])
        : one('SELECT * FROM product_categories WHERE name = $1 AND parent_id = $2', [name, parentId]));
    const ensure = async (name, parentId, sort) => {
        const row = await find(name, parentId);
        if (row) return row;
        return one(
            'INSERT INTO product_categories (name, parent_id, sort_order) VALUES ($1,$2,$3) RETURNING *',
            [name, parentId, sort]
        );
    };
    const roots = Object.entries(CATEGORY_TREE_SEED);
    for (let i = 0; i < roots.length; i += 1) {
        const [rootName, children] = roots[i];
        const root = await find(rootName, null);
        if (!root) continue;
        for (let j = 0; j < children.length; j += 1) {
            const child = children[j];
            const node = await ensure(child.name, root.id, j);
            const leaves = child.children || [];
            for (let k = 0; k < leaves.length; k += 1) {
                await ensure(leaves[k], node.id, k);
            }
        }
    }
}

function withCategoryDescendants(filters, tree) {
    if (!filters || !filters.category) return filters;
    return { ...filters, categoryNames: descendantCategoryNames(tree, filters.category) };
}

function categoryTreeFromRows(rows) {
    return buildCategoryTree((rows || []).map((row) => ({
        id: Number(row.id),
        name: row.name,
        parentId: row.parent_id == null ? null : Number(row.parent_id)
    })));
}

function attachSkillsToProducts(products, skillRows) {
    const byPid = new Map();
    skillRows.forEach((row) => {
        const pid = Number(row.product_id);
        if (!byPid.has(pid)) byPid.set(pid, []);
        byPid.get(pid).push({
            id: Number(row.id),
            slug: row.slug,
            title: row.title,
            impact: Number(row.impact || 1)
        });
    });
    return products.map((product) => ({
        ...product,
        skills: byPid.get(product.id) || product.skills || []
    }));
}

function seedDefaultsSqlite(db) {
    const vendor = db.prepare('SELECT * FROM shop_vendors WHERE slug = ?').get(INTERNAL_VENDOR.slug);
    if (!vendor) {
        db.prepare(`
            INSERT INTO shop_vendors (slug, display_name, kind, status, commission_pct, settlement_cycle)
            VALUES (?, ?, ?, ?, ?, ?)
        `).run(
            INTERNAL_VENDOR.slug,
            INTERNAL_VENDOR.displayName,
            INTERNAL_VENDOR.kind,
            INTERNAL_VENDOR.status,
            INTERNAL_VENDOR.commissionPct,
            INTERNAL_VENDOR.settlementCycle
        );
    }
    const insertSkill = db.prepare(
        'INSERT OR IGNORE INTO shop_skills (slug, title, description, sort_order) VALUES (?, ?, ?, ?)'
    );
    SKILLS.forEach((skill, index) => {
        insertSkill.run(skill.slug, skill.title, skill.description, index);
    });
}

function backfillSqlite(db) {
    const vendor = db.prepare('SELECT * FROM shop_vendors WHERE slug = ?').get(INTERNAL_VENDOR.slug);
    if (!vendor) return;
    db.prepare(`
        INSERT INTO shop_offers (product_id, vendor_id, price, stock, status)
        SELECT p.id, ?, p.price, p.stock, 'active'
        FROM products p
        WHERE NOT EXISTS (
            SELECT 1 FROM shop_offers o WHERE o.product_id = p.id AND o.vendor_id = ?
        )
    `).run(vendor.id, vendor.id);

    const products = db.prepare('SELECT id, category FROM products').all();
    const skillBySlug = new Map(
        db.prepare('SELECT * FROM shop_skills').all().map((row) => [row.slug, row])
    );
    const insertMeta = db.prepare(`
        INSERT OR IGNORE INTO shop_product_meta (product_id, age_band)
        VALUES (?, ?)
    `);
    const insertSkill = db.prepare(`
        INSERT OR IGNORE INTO shop_product_skills (product_id, skill_id, impact)
        VALUES (?, ?, 1)
    `);
    products.forEach((product) => {
        const defaults = CATEGORY_DEFAULTS[product.category] || { ageBand: '1-3', skills: ['cognitive'] };
        insertMeta.run(product.id, defaults.ageBand);
        defaults.skills.forEach((slug) => {
            const skill = skillBySlug.get(slug);
            if (skill) insertSkill.run(product.id, skill.id);
        });
    });
}

function ensureShopSchemaSqlite(db) {
    db.exec(SHOP_TABLES_SQLITE);
    if (!sqliteHasColumn(db, 'product_comments', 'rating')) {
        db.exec('ALTER TABLE product_comments ADD COLUMN rating INTEGER');
    }
    if (!sqliteHasColumn(db, 'product_categories', 'active')) {
        db.exec('ALTER TABLE product_categories ADD COLUMN active INTEGER NOT NULL DEFAULT 1');
    }
    seedDefaultsSqlite(db);
    backfillSqlite(db);
    seedShopExtrasSqlite(db);
}

function listSkillsSqlite(db) {
    return db.prepare('SELECT * FROM shop_skills ORDER BY sort_order, id').all().map(mapSkillRow);
}

function getInternalVendorSqlite(db) {
    return mapVendorRow(db.prepare('SELECT * FROM shop_vendors WHERE slug = ?').get(INTERNAL_VENDOR.slug));
}

function loadSkillsForProductsSqlite(db, products) {
    if (!products.length) return products;
    const ids = products.map((p) => p.id);
    const placeholders = ids.map(() => '?').join(',');
    const rows = db.prepare(`
        SELECT ps.product_id, ps.impact, s.id, s.slug, s.title
        FROM shop_product_skills ps
        JOIN shop_skills s ON s.id = ps.skill_id
        WHERE ps.product_id IN (${placeholders})
    `).all(...ids);
    return attachSkillsToProducts(products, rows);
}

function listCatalogSqlite(db, asBool, filters, options) {
    const tree = categoryTreeFromRows(db.prepare('SELECT id, name, parent_id FROM product_categories').all());
    const { sql, params } = buildCatalogSql(withCategoryDescendants(filters, tree), options);
    const rows = db.prepare(sql).all(...params).map((row) => mapCatalogRow(row, asBool));
    return loadSkillsForProductsSqlite(db, rows);
}

function enrichProductSqlite(db, asBool, product) {
    if (!product) return null;
    const rows = listCatalogSqlite(db, asBool, {}, { activeOnly: false }).filter((row) => row.id === product.id);
    const catalog = rows[0] || product;
    return {
        ...product,
        ...catalog,
        images: product.images,
        comments: product.comments
    };
}

function listCampaignSqlite(db) {
    return db.prepare('SELECT * FROM shop_campaigns WHERE active = 1 ORDER BY id DESC LIMIT 1').get() || null;
}

function listOffersForProductSqlite(db, productId) {
    return db.prepare(`
        SELECT o.*, v.display_name, v.kind, v.status AS vendor_status
        FROM shop_offers o
        JOIN shop_vendors v ON v.id = o.vendor_id
        WHERE o.product_id = ? AND o.status = 'active' AND v.status = 'active'
        ORDER BY o.price ASC, o.id ASC
    `).all(Number(productId)).map((row) => ({
        id: Number(row.id),
        productId: Number(row.product_id),
        vendorId: Number(row.vendor_id),
        vendorName: row.display_name,
        vendorKind: row.kind,
        price: Number(row.price),
        compareAtPrice: row.compare_at_price != null ? Number(row.compare_at_price) : null,
        stock: Number(row.stock || 0),
        sku: row.sku || null
    }));
}

function listVendorsSqlite(db) {
    return db.prepare('SELECT * FROM shop_vendors ORDER BY id DESC').all().map(mapVendorRow);
}

function getVendorByUserSqlite(db, userId) {
    return mapVendorRow(db.prepare('SELECT * FROM shop_vendors WHERE user_id = ?').get(Number(userId)));
}

function applyVendorSqlite(db, { userId, displayName, phone, docsNote }) {
    const existing = getVendorByUserSqlite(db, userId);
    if (existing) return existing;
    const info = db.prepare(`
        INSERT INTO shop_vendors (slug, display_name, kind, status, commission_pct, settlement_cycle, user_id, phone, docs_note)
        VALUES (?, ?, 'marketplace', 'pending', 8, 'weekly', ?, ?, ?)
    `).run(slugifyVendor(displayName), String(displayName || '').trim(), Number(userId), phone || null, docsNote || null);
    return mapVendorRow(db.prepare('SELECT * FROM shop_vendors WHERE id = ?').get(Number(info.lastInsertRowid)));
}

function updateVendorSqlite(db, id, patch) {
    const current = mapVendorRow(db.prepare('SELECT * FROM shop_vendors WHERE id = ?').get(Number(id)));
    if (!current) return null;
    const next = { ...current, ...patch };
    db.prepare(`
        UPDATE shop_vendors
        SET display_name = ?, status = ?, commission_pct = ?, settlement_cycle = ?, phone = ?, docs_note = ?
        WHERE id = ?
    `).run(
        next.displayName,
        next.status,
        Number(next.commissionPct || 0),
        next.settlementCycle || 'weekly',
        next.phone || null,
        next.docsNote || null,
        Number(id)
    );
    return mapVendorRow(db.prepare('SELECT * FROM shop_vendors WHERE id = ?').get(Number(id)));
}

function syncProductCommerceSqlite(db, productId, extra = {}) {
    const product = db.prepare('SELECT * FROM products WHERE id = ?').get(Number(productId));
    if (!product) return;
    const vendor = extra.vendorId
        ? db.prepare('SELECT * FROM shop_vendors WHERE id = ?').get(Number(extra.vendorId))
        : db.prepare('SELECT * FROM shop_vendors WHERE slug = ?').get(INTERNAL_VENDOR.slug);
    if (!vendor) return;
    const price = extra.price != null ? Number(extra.price) : Number(product.price);
    const stock = extra.stock != null ? Number(extra.stock) : Number(product.stock);
    const compareAt = extra.compareAtPrice != null && extra.compareAtPrice !== ''
        ? Number(extra.compareAtPrice)
        : null;
    const existing = db.prepare(
        'SELECT id FROM shop_offers WHERE product_id = ? AND vendor_id = ?'
    ).get(product.id, vendor.id);
    if (existing) {
        db.prepare(`
            UPDATE shop_offers
            SET price = ?, compare_at_price = ?, stock = ?, status = 'active'
            WHERE id = ?
        `).run(price, Number.isFinite(compareAt) ? compareAt : null, stock, existing.id);
    } else {
        db.prepare(`
            INSERT INTO shop_offers (product_id, vendor_id, price, compare_at_price, stock, status)
            VALUES (?, ?, ?, ?, ?, 'active')
        `).run(product.id, vendor.id, price, Number.isFinite(compareAt) ? compareAt : null, stock);
    }

    const ageBand = extra.ageBand || CATEGORY_DEFAULTS[product.category]?.ageBand || null;
    const brand = extra.brand != null ? String(extra.brand).trim() : '';
    const safetyWarning = extra.safetyWarning != null ? String(extra.safetyWarning).trim() : '';
    db.prepare(`
        INSERT INTO shop_product_meta (product_id, age_band, brand, safety_warning)
        VALUES (?, ?, ?, ?)
        ON CONFLICT(product_id) DO UPDATE SET
            age_band = excluded.age_band,
            brand = excluded.brand,
            safety_warning = excluded.safety_warning
    `).run(product.id, ageBand, brand || null, safetyWarning || null);

    if (Array.isArray(extra.skillIds) || Array.isArray(extra.skillSlugs)) {
        db.prepare('DELETE FROM shop_product_skills WHERE product_id = ?').run(product.id);
        const ids = Array.isArray(extra.skillIds)
            ? extra.skillIds.map(Number).filter(Boolean)
            : [];
        const slugs = Array.isArray(extra.skillSlugs) ? extra.skillSlugs : [];
        slugs.forEach((slug) => {
            const skill = db.prepare('SELECT id FROM shop_skills WHERE slug = ?').get(slug);
            if (skill) ids.push(Number(skill.id));
        });
        const insert = db.prepare(
            'INSERT OR IGNORE INTO shop_product_skills (product_id, skill_id, impact) VALUES (?, ?, 1)'
        );
        [...new Set(ids)].forEach((skillId) => insert.run(product.id, skillId));
    }
}

function adjustOfferStockSqlite(db, productId, delta) {
    db.prepare(`
        UPDATE shop_offers SET stock = MAX(0, stock + ?)
        WHERE product_id = ? AND status = 'active'
    `).run(Number(delta), Number(productId));
}

async function ensureShopSchemaPg(q, one, many) {
    await q(SHOP_TABLES_PG);
    await q('ALTER TABLE product_comments ADD COLUMN IF NOT EXISTS rating INTEGER');
    await q('ALTER TABLE product_categories ADD COLUMN IF NOT EXISTS active INTEGER NOT NULL DEFAULT 1');
    await q('ALTER TABLE shop_vendors ADD COLUMN IF NOT EXISTS user_id BIGINT');
    await q('ALTER TABLE shop_vendors ADD COLUMN IF NOT EXISTS phone TEXT');
    await q('ALTER TABLE shop_vendors ADD COLUMN IF NOT EXISTS docs_note TEXT');
    await q('ALTER TABLE banners ADD COLUMN IF NOT EXISTS placement TEXT');
    await q('ALTER TABLE banners ADD COLUMN IF NOT EXISTS product_id BIGINT');
    await q('ALTER TABLE banners ADD COLUMN IF NOT EXISTS sort_order INTEGER NOT NULL DEFAULT 0');
    await q('ALTER TABLE banners ADD COLUMN IF NOT EXISTS subtitle TEXT');
    await q("UPDATE banners SET placement = 'home' WHERE placement IS NULL OR placement = ''");

    const vendor = await one('SELECT * FROM shop_vendors WHERE slug = $1', [INTERNAL_VENDOR.slug]);
    if (!vendor) {
        await q(
            `INSERT INTO shop_vendors (slug, display_name, kind, status, commission_pct, settlement_cycle)
             VALUES ($1,$2,$3,$4,$5,$6)`,
            [
                INTERNAL_VENDOR.slug,
                INTERNAL_VENDOR.displayName,
                INTERNAL_VENDOR.kind,
                INTERNAL_VENDOR.status,
                INTERNAL_VENDOR.commissionPct,
                INTERNAL_VENDOR.settlementCycle
            ]
        );
    }
    for (let i = 0; i < SKILLS.length; i += 1) {
        const skill = SKILLS[i];
        await q(
            `INSERT INTO shop_skills (slug, title, description, sort_order)
             VALUES ($1,$2,$3,$4)
             ON CONFLICT (slug) DO NOTHING`,
            [skill.slug, skill.title, skill.description, i]
        );
    }

    const internal = await one('SELECT * FROM shop_vendors WHERE slug = $1', [INTERNAL_VENDOR.slug]);
    if (internal) {
        await q(
            `INSERT INTO shop_offers (product_id, vendor_id, price, stock, status)
             SELECT p.id, $1, p.price, p.stock, 'active'
             FROM products p
             WHERE NOT EXISTS (
                SELECT 1 FROM shop_offers o WHERE o.product_id = p.id AND o.vendor_id = $1
             )`,
            [internal.id]
        );
    }

    const products = await many('SELECT id, category FROM products');
    const skillRows = await many('SELECT * FROM shop_skills');
    const skillBySlug = new Map(skillRows.map((row) => [row.slug, row]));
    for (const product of products) {
        const defaults = CATEGORY_DEFAULTS[product.category] || { ageBand: '1-3', skills: ['cognitive'] };
        await q(
            `INSERT INTO shop_product_meta (product_id, age_band)
             VALUES ($1,$2)
             ON CONFLICT (product_id) DO NOTHING`,
            [product.id, defaults.ageBand]
        );
        for (const slug of defaults.skills) {
            const skill = skillBySlug.get(slug);
            if (skill) {
                await q(
                    `INSERT INTO shop_product_skills (product_id, skill_id, impact)
                     VALUES ($1,$2,1)
                     ON CONFLICT (product_id, skill_id) DO NOTHING`,
                    [product.id, skill.id]
                );
            }
        }
    }

    const campaign = await one('SELECT * FROM shop_campaigns WHERE active = 1 ORDER BY id DESC LIMIT 1');
    const now = Date.now();
    if (!campaign || (campaign.ends_at && new Date(campaign.ends_at).getTime() < now)) {
        const ends = new Date(now + 3 * 24 * 60 * 60 * 1000).toISOString();
        await q(
            `INSERT INTO shop_campaigns (title, kind, value, starts_at, ends_at, active)
             VALUES ($1,'percent',20,$2,$3,1)`,
            ['فروش ویژه', new Date(now).toISOString(), ends]
        );
    }
    const saleCount = await one(
        'SELECT COUNT(*)::int AS n FROM shop_offers WHERE compare_at_price IS NOT NULL AND compare_at_price > price'
    );
    if (saleCount && saleCount.n === 0) {
        await q(`
            UPDATE shop_offers
            SET compare_at_price = FLOOR(price * 1.35)
            WHERE id IN (SELECT id FROM shop_offers ORDER BY id LIMIT 4)
        `);
    }
    await seedCategoryTreePg(one, q);
}

function toPg(sql) {
    let index = 0;
    return String(sql).replace(/\?/g, () => `$${++index}`);
}

async function listSkillsPg(many) {
    return (await many('SELECT * FROM shop_skills ORDER BY sort_order, id')).map(mapSkillRow);
}

async function getInternalVendorPg(one) {
    return mapVendorRow(await one('SELECT * FROM shop_vendors WHERE slug = $1', [INTERNAL_VENDOR.slug]));
}

async function loadSkillsForProductsPg(many, products) {
    if (!products.length) return products;
    const ids = products.map((p) => p.id);
    const rows = await many(`
        SELECT ps.product_id, ps.impact, s.id, s.slug, s.title
        FROM shop_product_skills ps
        JOIN shop_skills s ON s.id = ps.skill_id
        WHERE ps.product_id = ANY($1::bigint[])
    `, [ids]);
    return attachSkillsToProducts(products, rows);
}

async function listCatalogPg(many, asBool, filters, options) {
    const tree = categoryTreeFromRows(await many('SELECT id, name, parent_id FROM product_categories'));
    const { sql, params } = buildCatalogSql(withCategoryDescendants(filters, tree), options);
    const rows = (await many(toPg(sql), params)).map((row) => mapCatalogRow(row, asBool));
    return loadSkillsForProductsPg(many, rows);
}

async function enrichProductPg(many, asBool, product) {
    if (!product) return null;
    const rows = await listCatalogPg(many, asBool, {}, { activeOnly: false });
    const catalog = rows.find((row) => row.id === product.id) || product;
    return {
        ...product,
        ...catalog,
        images: product.images,
        comments: product.comments
    };
}

async function listCampaignPg(one) {
    return one('SELECT * FROM shop_campaigns WHERE active = 1 ORDER BY id DESC LIMIT 1');
}

async function listOffersForProductPg(many, productId) {
    return (await many(`
        SELECT o.*, v.display_name, v.kind
        FROM shop_offers o
        JOIN shop_vendors v ON v.id = o.vendor_id
        WHERE o.product_id = $1 AND o.status = 'active' AND v.status = 'active'
        ORDER BY o.price ASC, o.id ASC
    `, [Number(productId)])).map((row) => ({
        id: Number(row.id),
        productId: Number(row.product_id),
        vendorId: Number(row.vendor_id),
        vendorName: row.display_name,
        vendorKind: row.kind,
        price: Number(row.price),
        compareAtPrice: row.compare_at_price != null ? Number(row.compare_at_price) : null,
        stock: Number(row.stock || 0),
        sku: row.sku || null
    }));
}

async function listVendorsPg(many) {
    return (await many('SELECT * FROM shop_vendors ORDER BY id DESC')).map(mapVendorRow);
}

async function getVendorByUserPg(one, userId) {
    return mapVendorRow(await one('SELECT * FROM shop_vendors WHERE user_id = $1', [Number(userId)]));
}

async function applyVendorPg(q, one, { userId, displayName, phone, docsNote }) {
    const existing = await getVendorByUserPg(one, userId);
    if (existing) return existing;
    const row = await one(
        `INSERT INTO shop_vendors (slug, display_name, kind, status, commission_pct, settlement_cycle, user_id, phone, docs_note)
         VALUES ($1,$2,'marketplace','pending',8,'weekly',$3,$4,$5) RETURNING *`,
        [slugifyVendor(displayName), String(displayName || '').trim(), Number(userId), phone || null, docsNote || null]
    );
    return mapVendorRow(row);
}

async function updateVendorPg(q, one, id, patch) {
    const current = mapVendorRow(await one('SELECT * FROM shop_vendors WHERE id = $1', [Number(id)]));
    if (!current) return null;
    const next = { ...current, ...patch };
    const row = await one(
        `UPDATE shop_vendors
         SET display_name=$1, status=$2, commission_pct=$3, settlement_cycle=$4, phone=$5, docs_note=$6
         WHERE id=$7 RETURNING *`,
        [next.displayName, next.status, Number(next.commissionPct || 0), next.settlementCycle || 'weekly', next.phone || null, next.docsNote || null, Number(id)]
    );
    return mapVendorRow(row);
}

async function syncProductCommercePg(q, one, productId, extra = {}) {
    const product = await one('SELECT * FROM products WHERE id = $1', [Number(productId)]);
    if (!product) return;
    const vendor = extra.vendorId
        ? await one('SELECT * FROM shop_vendors WHERE id = $1', [Number(extra.vendorId)])
        : await one('SELECT * FROM shop_vendors WHERE slug = $1', [INTERNAL_VENDOR.slug]);
    if (!vendor) return;
    const price = extra.price != null ? Number(extra.price) : Number(product.price);
    const stock = extra.stock != null ? Number(extra.stock) : Number(product.stock);
    const compareAt = extra.compareAtPrice != null && extra.compareAtPrice !== ''
        ? Number(extra.compareAtPrice)
        : null;
    await q(
        `INSERT INTO shop_offers (product_id, vendor_id, price, compare_at_price, stock, status)
         VALUES ($1,$2,$3,$4,$5,'active')
         ON CONFLICT (product_id, vendor_id) DO UPDATE SET
            price = EXCLUDED.price,
            compare_at_price = EXCLUDED.compare_at_price,
            stock = EXCLUDED.stock,
            status = 'active'`,
        [product.id, vendor.id, price, Number.isFinite(compareAt) ? compareAt : null, stock]
    );
    const ageBand = extra.ageBand || CATEGORY_DEFAULTS[product.category]?.ageBand || null;
    const brand = extra.brand != null ? String(extra.brand).trim() : '';
    const safetyWarning = extra.safetyWarning != null ? String(extra.safetyWarning).trim() : '';
    await q(
        `INSERT INTO shop_product_meta (product_id, age_band, brand, safety_warning)
         VALUES ($1,$2,$3,$4)
         ON CONFLICT (product_id) DO UPDATE SET
            age_band = EXCLUDED.age_band,
            brand = EXCLUDED.brand,
            safety_warning = EXCLUDED.safety_warning`,
        [product.id, ageBand, brand || null, safetyWarning || null]
    );
    if (Array.isArray(extra.skillIds) || Array.isArray(extra.skillSlugs)) {
        await q('DELETE FROM shop_product_skills WHERE product_id = $1', [product.id]);
        const ids = Array.isArray(extra.skillIds)
            ? extra.skillIds.map(Number).filter(Boolean)
            : [];
        const slugs = Array.isArray(extra.skillSlugs) ? extra.skillSlugs : [];
        for (const slug of slugs) {
            const skill = await one('SELECT id FROM shop_skills WHERE slug = $1', [slug]);
            if (skill) ids.push(Number(skill.id));
        }
        for (const skillId of [...new Set(ids)]) {
            await q(
                `INSERT INTO shop_product_skills (product_id, skill_id, impact)
                 VALUES ($1,$2,1)
                 ON CONFLICT (product_id, skill_id) DO NOTHING`,
                [product.id, skillId]
            );
        }
    }
}

async function adjustOfferStockPg(q, productId, delta, client) {
    await q(
        `UPDATE shop_offers SET stock = GREATEST(0, stock + $1)
         WHERE product_id = $2 AND status = 'active'`,
        [Number(delta), Number(productId)],
        client
    );
}

module.exports = {
    AGE_BANDS,
    SKILLS,
    INTERNAL_VENDOR,
    publicCommentAuthor,
    looksLikePhone,
    ensureShopSchemaSqlite,
    listSkillsSqlite,
    getInternalVendorSqlite,
    listCatalogSqlite,
    enrichProductSqlite,
    syncProductCommerceSqlite,
    adjustOfferStockSqlite,
    listCampaignSqlite,
    listOffersForProductSqlite,
    listVendorsSqlite,
    getVendorByUserSqlite,
    applyVendorSqlite,
    updateVendorSqlite,
    ensureShopSchemaPg,
    listSkillsPg,
    getInternalVendorPg,
    listCatalogPg,
    enrichProductPg,
    syncProductCommercePg,
    adjustOfferStockPg,
    listCampaignPg,
    listOffersForProductPg,
    listVendorsPg,
    getVendorByUserPg,
    applyVendorPg,
    updateVendorPg
};
